//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class addendadistribuidor
    {
        public int ID { get; set; }
        public string Clave { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Sucursal { get; set; }
        public string Addenda { get; set; }
    }
}
