//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class afd
    {
        public int ID { get; set; }
        public string Articulo { get; set; }
        public string Serie { get; set; }
        public Nullable<int> DepreciacionMeses { get; set; }
        public Nullable<decimal> DepreciacionImporte { get; set; }
        public Nullable<decimal> RevaluacionImporte { get; set; }
        public Nullable<decimal> RevaluacionAnterior { get; set; }
        public Nullable<System.DateTime> DRAnterior { get; set; }
        public string DescripcionSL { get; set; }
    
        public virtual articulo articulo1 { get; set; }
    }
}
