//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aftipo
    {
        public string Tipo { get; set; }
        public int MesesVidaUtil { get; set; }
        public int MesIniciaDepreciacion { get; set; }
        public string ContCuenta { get; set; }
        public string ContCuentaGasto { get; set; }
    }
}
