//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aiosreport
    {
        public string Reporte { get; set; }
        public string Descripcion { get; set; }
        public string SQL1 { get; set; }
        public string SQL2 { get; set; }
        public string SQL3 { get; set; }
        public string link1 { get; set; }
        public string link2 { get; set; }
        public string link3 { get; set; }
        public string key1 { get; set; }
        public string key2 { get; set; }
        public string key3 { get; set; }
        public byte[] Datos { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
