//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aioslog
    {
        public long ID { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Usuario { get; set; }
        public string IP { get; set; }
        public string Modulo { get; set; }
        public string Accion { get; set; }
        public string Mov { get; set; }
        public string MovID { get; set; }
        public string Estatus { get; set; }
        public string Texto { get; set; }
    }
}
