//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class almacen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public almacen()
        {
            this.invs = new HashSet<inv>();
            this.invs1 = new HashSet<inv>();
            this.prods = new HashSet<prod>();
            this.ventads = new HashSet<ventad>();
        }
    
        public string Almacen1 { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Colonia { get; set; }
        public string Poblacion { get; set; }
        public string Estado { get; set; }
        public string CodigoPostal { get; set; }
        public string Pais { get; set; }
        public string Tipo { get; set; }
        public int Sucursal { get; set; }
        public bool Utilizado { get; set; }
        public string Estatus { get; set; }
        public string ContCuenta { get; set; }
        public string CentroCostos { get; set; }
        public string Ruta { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public bool UsaUbicaciones { get; set; }
        public string ClienteConsigna { get; set; }
        public bool InvPlan { get; set; }
        public bool InvPlanTendenciaInterna { get; set; }
        public Nullable<decimal> InvPlanTendenciaFactor { get; set; }
        public Nullable<int> InvPlanDesvStockSeguridad { get; set; }
        public Nullable<int> InvPlanMinDiasStockSeg { get; set; }
        public Nullable<int> InvPlanMaxDiasStockSeg { get; set; }
        public Nullable<int> InvPlanDesvArtCriticos { get; set; }
        public Nullable<int> InvPlanInvSegMinArtCriticos { get; set; }
        public Nullable<int> InvPlanInvSegMaxArtCriticos { get; set; }
        public Nullable<int> InvPlanDiasInvSegReposicion { get; set; }
        public Nullable<decimal> InvPlanPorcAltoInusual { get; set; }
        public Nullable<decimal> InvPlanPorcBajoInusual { get; set; }
        public Nullable<decimal> InvPlanUsoInusualArtEspor { get; set; }
        public Nullable<decimal> InvPlanPorcAnualCostoMantto { get; set; }
        public Nullable<decimal> InvPlanCostoReabastecimiento { get; set; }
        public Nullable<int> InvPlanMesesMaxReabastecer { get; set; }
        public Nullable<int> InvPlanCicloOrdenDef { get; set; }
        public Nullable<int> InvPlanTiempoEsperaDef { get; set; }
        public Nullable<decimal> InvPlanTest1Estacional { get; set; }
        public Nullable<int> InvPlanTest2Estacional { get; set; }
        public Nullable<int> InvPlanTest3Estacional { get; set; }
        public Nullable<int> InvPlanMinMesesStock { get; set; }
        public Nullable<int> InvPlanUsoMesesStock { get; set; }
        public Nullable<int> InvPlanDiasExceso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inv> invs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inv> invs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prod> prods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ventad> ventads { get; set; }
    }
}
