//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class almacenubicacionesartft
    {
        public string Almacen { get; set; }
        public string Articulo { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<int> Pasillo { get; set; }
        public Nullable<int> Estante { get; set; }
        public Nullable<int> Nivel { get; set; }
        public Nullable<int> Seccion { get; set; }
    }
}
