//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class artcontactohist
    {
        public string Articulo { get; set; }
        public string Contacto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string NoParteProv { get; set; }
    }
}
