//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class artcontacto
    {
        public string Articulo { get; set; }
        public string Contacto { get; set; }
        public int Orden { get; set; }
        public string NoParteProv { get; set; }
        public string UnidadEmpaque { get; set; }
        public Nullable<int> DiasDev { get; set; }
        public Nullable<decimal> PorcPenaliza { get; set; }
        public Nullable<int> DiasEntrega { get; set; }
        public Nullable<bool> ElegRetorno { get; set; }
        public Nullable<int> DiasEntEmerg { get; set; }
        public Nullable<int> NumeroEntrega { get; set; }
    }
}
