//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulohit
    {
        public int Empresa { get; set; }
        public string Almacen { get; set; }
        public string Articulo { get; set; }
        public Nullable<int> MesActual { get; set; }
        public Nullable<int> Mes01 { get; set; }
        public Nullable<int> Mes02 { get; set; }
        public Nullable<int> Mes03 { get; set; }
        public Nullable<int> Mes04 { get; set; }
        public Nullable<int> Mes05 { get; set; }
        public Nullable<int> Mes06 { get; set; }
        public Nullable<int> Mes07 { get; set; }
        public Nullable<int> Mes08 { get; set; }
        public Nullable<int> Mes09 { get; set; }
        public Nullable<int> Mes10 { get; set; }
        public Nullable<int> Mes11 { get; set; }
        public Nullable<int> Mes12 { get; set; }
        public Nullable<int> Ultimos12Meses { get; set; }
        public Nullable<int> Ultimos06Meses { get; set; }
    }
}
