//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public articulo()
        {
            this.afcargas = new HashSet<afcarga>();
            this.afds = new HashSet<afd>();
            this.articulocomandaextras = new HashSet<articulocomandaextra>();
            this.articulokits = new HashSet<articulokit>();
            this.articulokitds = new HashSet<articulokitd>();
            this.articulounidads = new HashSet<articulounidad>();
            this.artmaterials = new HashSet<artmaterial>();
            this.cgds = new HashSet<cgd>();
            this.compiteotros = new HashSet<compiteotro>();
            this.invds = new HashSet<invd>();
            this.invtransfs = new HashSet<invtransf>();
            this.invtransfmats = new HashSet<invtransfmat>();
            this.manttods = new HashSet<manttod>();
            this.manttosolrefs = new HashSet<manttosolref>();
            this.pcds = new HashSet<pcd>();
            this.prodarticulooperacions = new HashSet<prodarticulooperacion>();
            this.prodds = new HashSet<prodd>();
            this.ventads = new HashSet<ventad>();
        }
    
        public string Articulo1 { get; set; }
        public string Descripcion { get; set; }
        public string Grupo { get; set; }
        public string Categoria { get; set; }
        public string Familia { get; set; }
        public string Linea { get; set; }
        public decimal Impuesto1 { get; set; }
        public Nullable<decimal> Impuesto2 { get; set; }
        public string Estatus { get; set; }
        public string Tipo { get; set; }
        public bool Utilizado { get; set; }
        public string ActivoFijoTipo { get; set; }
        public Nullable<decimal> RetencionIVA { get; set; }
        public Nullable<decimal> RetencionISR { get; set; }
        public string ContCuenta { get; set; }
        public bool SeProduce { get; set; }
        public string UnidadCompra { get; set; }
        public string UnidadVenta { get; set; }
        public string UnidadProd { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> Volumen { get; set; }
        public bool Comanda { get; set; }
        public Nullable<decimal> LoteMinimo { get; set; }
        public Nullable<decimal> CostoEstandar { get; set; }
        public Nullable<decimal> ProdCantidad { get; set; }
        public bool ValidarCaducidad { get; set; }
        public bool ValidarPeso { get; set; }
        public Nullable<int> DiasCaducidad { get; set; }
        public string Modelo { get; set; }
        public string PropiedadRenglon { get; set; }
        public string PropiedadColumna { get; set; }
        public Nullable<decimal> DeduciblePorcentaje { get; set; }
        public string ContCuentaOrden { get; set; }
        public bool Impuesto1Exento { get; set; }
        public bool Impuesto2Exento { get; set; }
        public Nullable<decimal> ImpuestoSH { get; set; }
        public Nullable<decimal> RetencionCedular { get; set; }
        public string DiasVencidos { get; set; }
        public string CodigoBarras { get; set; }
        public string Proveedor { get; set; }
        public string NombreProveedor { get; set; }
        public string CodigoProveedor { get; set; }
        public string FraccionArancelaria { get; set; }
        public System.DateTime UltimoCambio { get; set; }
        public string ContCuentaOrden2 { get; set; }
        public string Marca { get; set; }
        public string ModeloCE { get; set; }
        public string SubModeloCE { get; set; }
        public Nullable<decimal> IGI { get; set; }
        public Nullable<int> ImpuestoTipo { get; set; }
        public string ProductoServicio { get; set; }
        public string RetencionTipo { get; set; }
        public string ClaseGasto { get; set; }
        public bool DiotExcluir { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<decimal> MargenPorcentualModif { get; set; }
        public Nullable<bool> EsCore { get; set; }
        public string ArticuloCore { get; set; }
        public Nullable<bool> PoseeCore { get; set; }
        public Nullable<int> DiasADevolver { get; set; }
        public bool DePaso { get; set; }
        public string Descripcion2 { get; set; }
        public string Aplicacion { get; set; }
        public bool EsVIN { get; set; }
        public string AnoVIN { get; set; }
        public string MarcaVIN { get; set; }
        public string ModeloVIN { get; set; }
        public string TipoVIN { get; set; }
        public string CapacidadVIN { get; set; }
        public string RamaVIN { get; set; }
        public string ColorVIN { get; set; }
        public Nullable<bool> EsCarroceria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<afcarga> afcargas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<afd> afds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulocomandaextra> articulocomandaextras { get; set; }
        public virtual articuloimpuestotipo articuloimpuestotipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulokit> articulokits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulokitd> articulokitds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulounidad> articulounidads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<artmaterial> artmaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cgd> cgds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compiteotro> compiteotros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invd> invds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invtransf> invtransfs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invtransfmat> invtransfmats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<manttod> manttods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<manttosolref> manttosolrefs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pcd> pcds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prodarticulooperacion> prodarticulooperacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prodd> prodds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ventad> ventads { get; set; }
    }
}
