//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulocosto
    {
        public int Empresa { get; set; }
        public string Articulo { get; set; }
        public string Almacen { get; set; }
        public Nullable<decimal> CostoPromedio { get; set; }
        public Nullable<decimal> UltimoCosto { get; set; }
        public Nullable<System.DateTime> UltimaCompra { get; set; }
        public Nullable<System.DateTime> UltimaSalida { get; set; }
        public string UltimoProveedor { get; set; }
    }
}
