//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class articuloresuman
    {
        public int Empresa { get; set; }
        public string Articulo { get; set; }
        public string Almacen { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Existencia { get; set; }
        public Nullable<decimal> Notas { get; set; }
        public Nullable<decimal> Consig { get; set; }
        public Nullable<decimal> Reservado { get; set; }
        public Nullable<decimal> Disponible { get; set; }
        public Nullable<decimal> Transito { get; set; }
    }
}
