//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bc
    {
        public int ID { get; set; }
        public int Empresa { get; set; }
        public string Mov { get; set; }
        public int Sucursal { get; set; }
        public string Folio { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string Usuario { get; set; }
        public string Moneda { get; set; }
        public decimal TipoCambio { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> FechaConclusion { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public string Referencia { get; set; }
        public string Observaciones { get; set; }
        public string Concepto { get; set; }
        public string Proyecto { get; set; }
        public string Contacto { get; set; }
        public string CondicionPago { get; set; }
        public Nullable<System.DateTime> Vencimiento { get; set; }
        public string Cajero { get; set; }
        public string CuentaBanco { get; set; }
        public string CuentaBancoDestino { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> Impuestos { get; set; }
        public Nullable<decimal> Impuestos2 { get; set; }
        public Nullable<decimal> RetencionIVA { get; set; }
        public Nullable<decimal> RetencionISR { get; set; }
        public Nullable<decimal> ImpuestosFactor { get; set; }
        public Nullable<decimal> Impuestos2Factor { get; set; }
        public Nullable<decimal> RetIVAFactor { get; set; }
        public Nullable<decimal> RetISRFactor { get; set; }
        public string OrigenModulo { get; set; }
        public Nullable<int> OrigenID { get; set; }
        public string MonedaAplica { get; set; }
        public Nullable<decimal> TipoCambioAplica { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public string CentroCostos { get; set; }
        public Nullable<decimal> Cambio { get; set; }
        public string WFEstado { get; set; }
        public string WFUsuario { get; set; }
        public string CadenaOriginal { get; set; }
        public string SelloDigital { get; set; }
        public string Aprobacion { get; set; }
        public string Serie { get; set; }
        public Nullable<long> Consecutivo { get; set; }
        public string NumeroAprobacion { get; set; }
        public string Inicial { get; set; }
        public string Final { get; set; }
        public string CertificadoSerie { get; set; }
        public string FechaHora { get; set; }
        public string XML { get; set; }
        public byte[] CodigoBidimensional { get; set; }
        public string UUID { get; set; }
        public string LlaveCertificado { get; set; }
        public string XMLCancelado { get; set; }
        public string XMLCanceladoFecha { get; set; }
        public string PacCadenaOriginal { get; set; }
        public string PacSelloCFD { get; set; }
        public string PacSelloSat { get; set; }
        public string PacVersion { get; set; }
        public string PacNoCertificado { get; set; }
        public string PacFechaTimbrado { get; set; }
        public Nullable<decimal> ImpuestosSH { get; set; }
        public Nullable<decimal> ImpuestosSHFactor { get; set; }
        public Nullable<decimal> RetencionCedular { get; set; }
        public Nullable<decimal> RetCedularFactor { get; set; }
        public Nullable<decimal> Retencion5PM { get; set; }
        public string Agente { get; set; }
        public bool VencimientoIncentivoAp { get; set; }
        public string Contacto2 { get; set; }
        public Nullable<decimal> PagImpGral { get; set; }
        public Nullable<decimal> PagUltimoImp { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string Vin { get; set; }
        public string IDportal { get; set; }
        public string Ticket { get; set; }
        public string EstatusPortal { get; set; }
        public string FacturaProvNac { get; set; }
        public string Dealer { get; set; }
        public string OrdenCompraPortal { get; set; }
        public Nullable<decimal> PorcDescuentoPP { get; set; }
    }
}
