//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bcaplicadif
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public string MovAplicaDif { get; set; }
        public string ConceptoAplicaDif { get; set; }
        public string ReferenciaAplicaDif { get; set; }
        public decimal ImporteAplicaDif { get; set; }
        public decimal ImpuestosAplicaDif { get; set; }
    }
}
