//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bcconsecutivo
    {
        public int Empresa { get; set; }
        public string Mov { get; set; }
        public int Sucursal { get; set; }
        public int Folio { get; set; }
        public string CuentaBanco { get; set; }
        public string FolioInicial { get; set; }
        public string FolioFinal { get; set; }
        public string Serie { get; set; }
        public string NumeroAprobacion { get; set; }
        public string Aprobacion { get; set; }
        public string DonatariaFechaAutorizacion { get; set; }
        public string DonatariaNumeroAutorizacion { get; set; }
        public string CertificadoSerie { get; set; }
    }
}
