//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class busquedaavanzadab
    {
        public int Empresa { get; set; }
        public string Usuario { get; set; }
        public string Sender { get; set; }
        public string Campo { get; set; }
        public string CampoValor { get; set; }
        public string Filtro { get; set; }
        public string Valor { get; set; }
        public string Boton { get; set; }
        public Nullable<int> TipoCampo { get; set; }
    }
}
