//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calidadquickcheck
    {
        public int ID { get; set; }
        public int IDInternoI { get; set; }
        public Nullable<bool> VerdeM { get; set; }
        public Nullable<bool> AmarilloM { get; set; }
        public Nullable<bool> RojoM { get; set; }
        public string ComentarioM { get; set; }
        public Nullable<bool> Verde { get; set; }
        public Nullable<bool> Amarillo { get; set; }
        public Nullable<bool> Rojo { get; set; }
        public string Comentario { get; set; }
    }
}
