//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calidadevaluacionesdd
    {
        public int ID { get; set; }
        public string Modulo { get; set; }
        public int RenglonID { get; set; }
        public string Actividad { get; set; }
        public string ConceptoEvaluacion { get; set; }
        public string Evaluacion { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Concepto { get; set; }
        public Nullable<int> Valor { get; set; }
        public bool Califica { get; set; }
    }
}
