//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calidadrequisitod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public calidadrequisitod()
        {
            this.calidadrequisitodtareas = new HashSet<calidadrequisitodtarea>();
        }
    
        public string CalidadRequisito { get; set; }
        public string Control { get; set; }
        public Nullable<int> Frecuencia { get; set; }
        public string Unidad { get; set; }
        public string Dias { get; set; }
        public string Prioridad { get; set; }
        public string Modulo { get; set; }
        public string Movimiento { get; set; }
        public string Duracion { get; set; }
        public string AgenteResponsable { get; set; }
        public Nullable<bool> GenerarAleatorio { get; set; }
        public Nullable<int> Minimo { get; set; }
        public Nullable<int> Maximo { get; set; }
        public string PeriodoAleatorio { get; set; }
    
        public virtual calidadrequisito calidadrequisito1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calidadrequisitodtarea> calidadrequisitodtareas { get; set; }
    }
}
