//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calidad
    {
        public int ID { get; set; }
        public int Empresa { get; set; }
        public string Mov { get; set; }
        public int Sucursal { get; set; }
        public string Folio { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string Usuario { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> FechaConclusion { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public string Concepto { get; set; }
        public string Proyecto { get; set; }
        public string Referencia { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaProgramada { get; set; }
        public string Norma { get; set; }
        public string Requisito { get; set; }
        public string Control { get; set; }
        public string Prioridad { get; set; }
        public string Documento { get; set; }
        public string AgenteResponsable { get; set; }
        public string MovReferencia { get; set; }
        public string OrigenModulo { get; set; }
        public Nullable<int> OrigenID { get; set; }
        public string WFEstado { get; set; }
        public string WFUsuario { get; set; }
        public string MovAplica { get; set; }
        public string Equipo { get; set; }
        public string Descripcion { get; set; }
        public string VIN { get; set; }
    }
}
