//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calidadrequisitodtarea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public calidadrequisitodtarea()
        {
            this.calidadrequisitodtareaes = new HashSet<calidadrequisitodtareae>();
            this.calidadrequisitodtareaux = new HashSet<calidadrequisitodtareau>();
        }
    
        public string CalidadRequisito { get; set; }
        public string Control { get; set; }
        public int Numero { get; set; }
        public string Actividad { get; set; }
        public int Cantidad { get; set; }
        public Nullable<int> DuracionCantidad { get; set; }
        public string DuracionUnidad { get; set; }
    
        public virtual calidadrequisitod calidadrequisitod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calidadrequisitodtareae> calidadrequisitodtareaes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calidadrequisitodtareau> calidadrequisitodtareaux { get; set; }
    }
}
