//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class calidadd
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Actividad { get; set; }
        public Nullable<int> UbicacionD { get; set; }
        public bool Pendiente { get; set; }
        public bool Avanzar { get; set; }
        public Nullable<int> AplicaID { get; set; }
        public string AgenteD { get; set; }
        public string FechaHoraInicio { get; set; }
        public string DuracionEstimada { get; set; }
        public string DuracionReal { get; set; }
        public string ObservacionesD { get; set; }
        public string ControlRevision { get; set; }
        public Nullable<int> Cuadrilla { get; set; }
        public string EstatusEvaluacion { get; set; }
    }
}
