//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class camsolagendaed
    {
        public int PID { get; set; }
        public string AplicaMov { get; set; }
        public string Plantilla { get; set; }
        public string Estatus { get; set; }
        public string Agente { get; set; }
        public string Resultado { get; set; }
        public Nullable<bool> Efectiva { get; set; }
        public string Observaciones { get; set; }
        public string CausaNoEfec { get; set; }
    }
}
