//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class camsolcostocarroceriaview
    {
        public int IDInterno { get; set; }
        public string TipoUnidadD { get; set; }
        public string ModeloD { get; set; }
        public string ProveedorD { get; set; }
        public string CarroceriaD { get; set; }
        public string MonedaD { get; set; }
        public Nullable<decimal> DescuentoALD { get; set; }
        public Nullable<decimal> CostoActD { get; set; }
        public Nullable<decimal> CostoAntD { get; set; }
        public string EstatusD { get; set; }
        public string NombreProveedorD { get; set; }
    }
}
