//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class camsolcotizcondfinanciera
    {
        public int IDCredito { get; set; }
        public Nullable<decimal> AFMes12TasaPesos { get; set; }
        public Nullable<decimal> AFMes24TasaPesos { get; set; }
        public Nullable<decimal> AFMes36TasaPesos { get; set; }
        public Nullable<decimal> AFMes48TasaPesos { get; set; }
        public Nullable<decimal> AFMes60TasaPesos { get; set; }
        public Nullable<decimal> AFMes72TasaPesos { get; set; }
        public Nullable<decimal> AFMes12TasaDolares { get; set; }
        public Nullable<decimal> AFMes24TasaDolares { get; set; }
        public Nullable<decimal> AFMes36TasaDolares { get; set; }
        public Nullable<decimal> AFMes48TasaDolares { get; set; }
        public Nullable<decimal> AFMes60TasaDolares { get; set; }
        public Nullable<decimal> AFMes72TasaDolares { get; set; }
        public Nullable<decimal> AFMes12OpcionCompra { get; set; }
        public Nullable<decimal> AFMes24OpcionCompra { get; set; }
        public Nullable<decimal> AFMes36OpcionCompra { get; set; }
        public Nullable<decimal> AFMes48OpcionCompra { get; set; }
        public Nullable<decimal> AFMes60OpcionCompra { get; set; }
        public Nullable<decimal> AFMes72OpcionCompra { get; set; }
        public Nullable<decimal> AFMes12RentasDeposito { get; set; }
        public Nullable<decimal> AFMes24RentasDeposito { get; set; }
        public Nullable<decimal> AFMes36RentasDeposito { get; set; }
        public Nullable<decimal> AFMes48RentasDeposito { get; set; }
        public Nullable<decimal> AFMes60RentasDeposito { get; set; }
        public Nullable<decimal> AFMes72RentasDeposito { get; set; }
        public Nullable<decimal> AFMes12Comision { get; set; }
        public Nullable<decimal> AFMes24Comision { get; set; }
        public Nullable<decimal> AFMes36Comision { get; set; }
        public Nullable<decimal> AFMes48Comision { get; set; }
        public Nullable<decimal> AFMes60Comision { get; set; }
        public Nullable<decimal> AFMes72Comision { get; set; }
        public Nullable<decimal> AFMes12GastosContratMX { get; set; }
        public Nullable<decimal> AFMes24GastosContratMX { get; set; }
        public Nullable<decimal> AFMes36GastosContratMX { get; set; }
        public Nullable<decimal> AFMes48GastosContratMX { get; set; }
        public Nullable<decimal> AFMes60GastosContratMX { get; set; }
        public Nullable<decimal> AFMes72GastosContratMX { get; set; }
        public Nullable<decimal> AFMes12GastosContratDls { get; set; }
        public Nullable<decimal> AFMes24GastosContratDls { get; set; }
        public Nullable<decimal> AFMes36GastosContratDls { get; set; }
        public Nullable<decimal> AFMes48GastosContratDls { get; set; }
        public Nullable<decimal> AFMes60GastosContratDls { get; set; }
        public Nullable<decimal> AFMes72GastosContratDls { get; set; }
        public Nullable<decimal> CSMes12TasaPesos { get; set; }
        public Nullable<decimal> CSMes24TasaPesos { get; set; }
        public Nullable<decimal> CSMes36TasaPesos { get; set; }
        public Nullable<decimal> CSMes48TasaPesos { get; set; }
        public Nullable<decimal> CSMes60TasaPesos { get; set; }
        public Nullable<decimal> CSMes72TasaPesos { get; set; }
        public Nullable<decimal> CSMes12TasaDolares { get; set; }
        public Nullable<decimal> CSMes24TasaDolares { get; set; }
        public Nullable<decimal> CSMes36TasaDolares { get; set; }
        public Nullable<decimal> CSMes48TasaDolares { get; set; }
        public Nullable<decimal> CSMes60TasaDolares { get; set; }
        public Nullable<decimal> CSMes72TasaDolares { get; set; }
        public Nullable<decimal> CSMes12RentasDeposito { get; set; }
        public Nullable<decimal> CSMes24RentasDeposito { get; set; }
        public Nullable<decimal> CSMes36RentasDeposito { get; set; }
        public Nullable<decimal> CSMes48RentasDeposito { get; set; }
        public Nullable<decimal> CSMes60RentasDeposito { get; set; }
        public Nullable<decimal> CSMes72RentasDeposito { get; set; }
        public Nullable<decimal> CSMes12Comision { get; set; }
        public Nullable<decimal> CSMes24Comision { get; set; }
        public Nullable<decimal> CSMes36Comision { get; set; }
        public Nullable<decimal> CSMes48Comision { get; set; }
        public Nullable<decimal> CSMes60Comision { get; set; }
        public Nullable<decimal> CSMes72Comision { get; set; }
        public Nullable<decimal> CSMes12GastosContratMX { get; set; }
        public Nullable<decimal> CSMes24GastosContratMX { get; set; }
        public Nullable<decimal> CSMes36GastosContratMX { get; set; }
        public Nullable<decimal> CSMes48GastosContratMX { get; set; }
        public Nullable<decimal> CSMes60GastosContratMX { get; set; }
        public Nullable<decimal> CSMes72GastosContratMX { get; set; }
        public Nullable<decimal> CSMes12GastosContratDls { get; set; }
        public Nullable<decimal> CSMes24GastosContratDls { get; set; }
        public Nullable<decimal> CSMes36GastosContratDls { get; set; }
        public Nullable<decimal> CSMes48GastosContratDls { get; set; }
        public Nullable<decimal> CSMes60GastosContratDls { get; set; }
        public Nullable<decimal> CSMes72GastosContratDls { get; set; }
        public Nullable<decimal> APMes12TasaPesos { get; set; }
        public Nullable<decimal> APMes24TasaPesos { get; set; }
        public Nullable<decimal> APMes36TasaPesos { get; set; }
        public Nullable<decimal> APMes48TasaPesos { get; set; }
        public Nullable<decimal> APMes60TasaPesos { get; set; }
        public Nullable<decimal> APMes72TasaPesos { get; set; }
        public Nullable<decimal> APMes12TasaDolares { get; set; }
        public Nullable<decimal> APMes24TasaDolares { get; set; }
        public Nullable<decimal> APMes36TasaDolares { get; set; }
        public Nullable<decimal> APMes48TasaDolares { get; set; }
        public Nullable<decimal> APMes60TasaDolares { get; set; }
        public Nullable<decimal> APMes72TasaDolares { get; set; }
        public Nullable<decimal> APMes12ValorResidual { get; set; }
        public Nullable<decimal> APMes24ValorResidual { get; set; }
        public Nullable<decimal> APMes36ValorResidual { get; set; }
        public Nullable<decimal> APMes48ValorResidual { get; set; }
        public Nullable<decimal> APMes60ValorResidual { get; set; }
        public Nullable<decimal> APMes72ValorResidual { get; set; }
        public Nullable<decimal> APMes12RentasDeposito { get; set; }
        public Nullable<decimal> APMes24RentasDeposito { get; set; }
        public Nullable<decimal> APMes36RentasDeposito { get; set; }
        public Nullable<decimal> APMes48RentasDeposito { get; set; }
        public Nullable<decimal> APMes60RentasDeposito { get; set; }
        public Nullable<decimal> APMes72RentasDeposito { get; set; }
        public Nullable<decimal> APMes12Comision { get; set; }
        public Nullable<decimal> APMes24Comision { get; set; }
        public Nullable<decimal> APMes36Comision { get; set; }
        public Nullable<decimal> APMes48Comision { get; set; }
        public Nullable<decimal> APMes60Comision { get; set; }
        public Nullable<decimal> APMes72Comision { get; set; }
        public Nullable<decimal> APMes12GastosContratMX { get; set; }
        public Nullable<decimal> APMes24GastosContratMX { get; set; }
        public Nullable<decimal> APMes36GastosContratMX { get; set; }
        public Nullable<decimal> APMes48GastosContratMX { get; set; }
        public Nullable<decimal> APMes60GastosContratMX { get; set; }
        public Nullable<decimal> APMes72GastosContratMX { get; set; }
        public Nullable<decimal> APMes12GastosContratDls { get; set; }
        public Nullable<decimal> APMes24GastosContratDls { get; set; }
        public Nullable<decimal> APMes36GastosContratDls { get; set; }
        public Nullable<decimal> APMes48GastosContratDls { get; set; }
        public Nullable<decimal> APMes60GastosContratDls { get; set; }
        public Nullable<decimal> APMes72GastosContratDls { get; set; }
        public Nullable<decimal> APMes12Sobreprecio { get; set; }
        public Nullable<decimal> APMes24Sobreprecio { get; set; }
        public Nullable<decimal> APMes36Sobreprecio { get; set; }
        public Nullable<decimal> APMes48Sobreprecio { get; set; }
        public Nullable<decimal> APMes60Sobreprecio { get; set; }
        public Nullable<decimal> APMes72Sobreprecio { get; set; }
    }
}
