//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class camsolpresupventacli
    {
        public int ID { get; set; }
        public string ClienteC { get; set; }
        public string NombreCliente { get; set; }
        public string PVEH { get; set; }
        public string Potencial { get; set; }
        public string VentaPromMes { get; set; }
        public string PorcMShare { get; set; }
        public string ObjetivoAnual { get; set; }
    }
}
