//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class camsolcotizcostoaciento
    {
        public int IDVariante { get; set; }
        public string Proveedora { get; set; }
        public Nullable<decimal> InyectableAnt { get; set; }
        public Nullable<decimal> InyectableAct { get; set; }
        public Nullable<decimal> InyectableTelaAnt { get; set; }
        public Nullable<decimal> InyectableTelaAct { get; set; }
        public Nullable<decimal> AltosTelaAnt { get; set; }
        public Nullable<decimal> AltosTelaAct { get; set; }
        public Nullable<decimal> AltosReclinablesAnt { get; set; }
        public Nullable<decimal> AltosReclinablesAct { get; set; }
        public Nullable<decimal> TropicalAnt { get; set; }
        public Nullable<decimal> TropicalAct { get; set; }
        public Nullable<System.DateTime> FechaModAsientos { get; set; }
        public string ProvaAnt { get; set; }
        public string ProvaAct { get; set; }
        public Nullable<System.DateTime> FechaModProvact { get; set; }
        public string Proveedora2 { get; set; }
        public Nullable<decimal> InyectableAnt2 { get; set; }
        public Nullable<decimal> InyectableAct2 { get; set; }
        public Nullable<decimal> InyectableTelaAnt2 { get; set; }
        public Nullable<decimal> InyectableTelaAct2 { get; set; }
        public Nullable<decimal> AltosTelaAnt2 { get; set; }
        public Nullable<decimal> AltosTelaAct2 { get; set; }
        public Nullable<decimal> AltosReclinablesAnt2 { get; set; }
        public Nullable<decimal> AltosReclinablesAct2 { get; set; }
        public Nullable<decimal> TropicalAnt2 { get; set; }
        public Nullable<decimal> TropicalAct2 { get; set; }
        public Nullable<System.DateTime> FechaModAsientos2 { get; set; }
        public string ProvaAnt2 { get; set; }
        public string ProvaAct2 { get; set; }
        public Nullable<System.DateTime> FechaModProvact2 { get; set; }
        public string Proveedora3 { get; set; }
        public Nullable<decimal> InyectableAnt3 { get; set; }
        public Nullable<decimal> InyectableAct3 { get; set; }
        public Nullable<decimal> InyectableTelaAnt3 { get; set; }
        public Nullable<decimal> InyectableTelaAct3 { get; set; }
        public Nullable<decimal> AltosTelaAnt3 { get; set; }
        public Nullable<decimal> AltosTelaAct3 { get; set; }
        public Nullable<decimal> AltosReclinablesAnt3 { get; set; }
        public Nullable<decimal> AltosReclinablesAct3 { get; set; }
        public Nullable<decimal> TropicalAnt3 { get; set; }
        public Nullable<decimal> TropicalAct3 { get; set; }
        public Nullable<System.DateTime> FechaModAsientos3 { get; set; }
        public string ProvaAnt3 { get; set; }
        public string ProvaAct3 { get; set; }
        public Nullable<System.DateTime> FechaModProvact3 { get; set; }
        public string Proveedora4 { get; set; }
        public Nullable<decimal> InyectableAnt4 { get; set; }
        public Nullable<decimal> InyectableAct4 { get; set; }
        public Nullable<decimal> InyectableTelaAnt4 { get; set; }
        public Nullable<decimal> InyectableTelaAct4 { get; set; }
        public Nullable<decimal> AltosTelaAnt4 { get; set; }
        public Nullable<decimal> AltosTelaAct4 { get; set; }
        public Nullable<decimal> AltosReclinablesAnt4 { get; set; }
        public Nullable<decimal> AltosReclinablesAct4 { get; set; }
        public Nullable<decimal> TropicalAnt4 { get; set; }
        public Nullable<decimal> TropicalAct4 { get; set; }
        public Nullable<System.DateTime> FechaModAsientos4 { get; set; }
        public string ProvaAnt4 { get; set; }
        public string ProvaAct4 { get; set; }
        public Nullable<System.DateTime> FechaModProvact4 { get; set; }
        public Nullable<int> ProveedorSelectAnt { get; set; }
        public Nullable<int> ProveedorSelectAct { get; set; }
        public Nullable<System.DateTime> FechaActProvSel { get; set; }
    }
}
