//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class camsolagendacatalogo
    {
        public int IDInterno { get; set; }
        public string Contacto { get; set; }
        public string NombreContacto { get; set; }
        public Nullable<int> CantidadCitas { get; set; }
        public string Periodo { get; set; }
        public string Agente { get; set; }
        public string NombreAgente { get; set; }
        public string Asunto { get; set; }
        public string Objetivo { get; set; }
        public Nullable<bool> Generado { get; set; }
        public Nullable<bool> SelecDias { get; set; }
    }
}
