//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class camsolagendaprevio
    {
        public int IDInterno { get; set; }
        public System.DateTime FechaIniciod { get; set; }
        public string HoraIniciod { get; set; }
        public System.DateTime FechaFind { get; set; }
        public string HoraFind { get; set; }
        public string Contactod { get; set; }
        public string ContactoCliented { get; set; }
        public string Asuntod { get; set; }
        public string Observacionesd { get; set; }
        public string Estatusd { get; set; }
        public string Agented { get; set; }
        public string Resultadod { get; set; }
        public Nullable<bool> Efectivad { get; set; }
        public string Oportunidadd { get; set; }
        public string GrupoContratod { get; set; }
        public string Objetivod { get; set; }
        public string NombreContactod { get; set; }
        public string CausaNoEfecd { get; set; }
        public string NombreContactoCliented { get; set; }
        public string NombreAgented { get; set; }
    }
}
