//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class camsolmargenlinea
    {
        public string Linea { get; set; }
        public string SubLinea { get; set; }
        public string Marca { get; set; }
        public decimal Margen { get; set; }
        public decimal DescGlobalMax { get; set; }
        public bool IncluirCore { get; set; }
    }
}
