//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class camsolpromocionesd
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public string Linea { get; set; }
        public string SubLinea { get; set; }
        public string Marca { get; set; }
        public string Articulo { get; set; }
        public string TipoDescuentoP { get; set; }
        public Nullable<decimal> CantidadDescuentoP { get; set; }
        public Nullable<decimal> CantidadP { get; set; }
        public Nullable<decimal> CantidadProvP { get; set; }
        public string ClienteP { get; set; }
        public string SegmentoP { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> CantidadPeriodo { get; set; }
        public string Periodo { get; set; }
    }
}
