//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class camsolcostoaccesorio
    {
        public int IDInterno { get; set; }
        public string Articulo { get; set; }
        public string Descripcion2 { get; set; }
        public decimal CantidadUnidad { get; set; }
        public decimal Costo { get; set; }
        public Nullable<bool> Incluido { get; set; }
        public string Unidad { get; set; }
        public int RenglonID { get; set; }
    }
}
