//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class centrocosto
    {
        public int Empresa { get; set; }
        public string CentroCostos { get; set; }
        public string Nombre { get; set; }
        public bool Utilizado { get; set; }
        public string Estatus { get; set; }
        public string Grupo { get; set; }
        public string Almacen { get; set; }
        public Nullable<bool> Principal { get; set; }
    }
}
