//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class centrocostosd
    {
        public string CentroCostos { get; set; }
        public string CentroCostosD1 { get; set; }
        public decimal PorcProrrateo { get; set; }
        public int Sucursal { get; set; }
    }
}
