//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfdiuuidrelacionado
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public string Modulo { get; set; }
        public Nullable<int> IDOrigen { get; set; }
        public string ModuloOrigen { get; set; }
        public string UUID { get; set; }
    }
}
