//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfdirespuesta
    {
        public int ID { get; set; }
        public string UUID { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Proceso { get; set; }
        public string fecha { get; set; }
        public string Codigo { get; set; }
        public string Estatus { get; set; }
        public string Mensaje { get; set; }
        public string rfcReceptor { get; set; }
        public string rfcPac { get; set; }
        public string EstatusCancelacion { get; set; }
        public string AcuseXML { get; set; }
    }
}
