//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfdi
    {
        public int ID { get; set; }
        public string Modulo { get; set; }
        public string CadenaOriginal { get; set; }
        public string SelloDigital { get; set; }
        public string CertificadoSerie { get; set; }
        public string XML { get; set; }
        public byte[] CodigoBidimensional { get; set; }
        public string UUID { get; set; }
        public string XMLCancelado { get; set; }
        public string XMLCanceladoFecha { get; set; }
        public string PacCadenaOriginal { get; set; }
        public string PacSelloCFD { get; set; }
        public string PacSelloSat { get; set; }
        public string PacVersion { get; set; }
        public string PacNoCertificado { get; set; }
        public string PacFechaTimbrado { get; set; }
        public string RutaArchivoXML { get; set; }
        public string RfcProvCertif { get; set; }
        public string Leyenda { get; set; }
        public Nullable<bool> Timbre { get; set; }
        public string Certificado { get; set; }
        public string LlaveCertificado { get; set; }
        public Nullable<decimal> ImporteCFDI { get; set; }
        public string RFCEmisor { get; set; }
        public string RFCReceptor { get; set; }
    }
}
