//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfdibccomplementod
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public int IDAplica { get; set; }
        public string Mov { get; set; }
        public string Folio { get; set; }
        public string Serie { get; set; }
        public string MonedaDR { get; set; }
        public Nullable<decimal> TipoCambioDR { get; set; }
        public string UUID { get; set; }
        public Nullable<decimal> ImporteAplica { get; set; }
        public Nullable<int> NumParcialidad { get; set; }
        public Nullable<decimal> ImpSaldoAnt { get; set; }
    }
}
