//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cgapoyoproveedor
    {
        public int IDInterno { get; set; }
        public Nullable<int> ID { get; set; }
        public string Mov { get; set; }
        public string Folio { get; set; }
        public string Contacto { get; set; }
        public string TipoDescuento { get; set; }
        public string NombrePromo { get; set; }
        public Nullable<decimal> PorcApoyo { get; set; }
        public Nullable<decimal> ImporteApoyo { get; set; }
        public string Proveedor { get; set; }
        public string MovApoyoProv { get; set; }
        public string ConceptoApoyoProv { get; set; }
        public Nullable<int> IDCg { get; set; }
        public Nullable<bool> Cancelado { get; set; }
    }
}
