//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cgcto
    {
        public int IDInterno { get; set; }
        public int PID { get; set; }
        public int ID { get; set; }
        public string Mov { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string Articulo { get; set; }
        public decimal Cantidad { get; set; }
        public Nullable<decimal> CantidadUnidad { get; set; }
        public string Unidad { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> DescuentoLinea { get; set; }
        public Nullable<decimal> CantidadDevolver { get; set; }
        public Nullable<decimal> DescuentoImporte { get; set; }
        public Nullable<int> RenglonID { get; set; }
    }
}
