//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cgd
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public string ContactoD { get; set; }
        public string ReferenciaD { get; set; }
        public string Articulo { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public decimal Costo { get; set; }
        public Nullable<decimal> CostoInv { get; set; }
        public Nullable<decimal> DescLinea { get; set; }
        public decimal Impuesto1 { get; set; }
        public Nullable<decimal> Impuesto2 { get; set; }
        public Nullable<decimal> RetencionIVA { get; set; }
        public Nullable<decimal> RetencionISR { get; set; }
        public Nullable<int> AplicaID { get; set; }
        public Nullable<decimal> CantidadPendiente { get; set; }
        public Nullable<decimal> ImporteD { get; set; }
        public Nullable<decimal> Impuesto1ImporteD { get; set; }
        public Nullable<decimal> Impuesto2ImporteD { get; set; }
        public Nullable<decimal> RetIVAImporteD { get; set; }
        public Nullable<decimal> RetISRImporteD { get; set; }
        public string CentroCostosD { get; set; }
        public Nullable<int> KitRenglonID { get; set; }
        public Nullable<int> RenglonControl { get; set; }
        public Nullable<decimal> CantidadUnidad { get; set; }
        public string Unidad { get; set; }
        public float Factor { get; set; }
        public Nullable<decimal> CantidadA { get; set; }
        public Nullable<decimal> Cubicaje { get; set; }
        public string Modelo { get; set; }
        public string Renglon { get; set; }
        public string Columna { get; set; }
        public string PropiedadRenglon { get; set; }
        public string PropiedadColumna { get; set; }
        public Nullable<decimal> DeduciblePorcentaje { get; set; }
        public Nullable<decimal> DeducibleImporte { get; set; }
        public Nullable<decimal> ImpuestoSH { get; set; }
        public Nullable<decimal> ImpuestoSHImporteD { get; set; }
        public Nullable<decimal> RetencionCedular { get; set; }
        public Nullable<decimal> RetCedularImporteD { get; set; }
        public Nullable<bool> Transferido { get; set; }
        public string JamcoLote { get; set; }
        public Nullable<decimal> ValorAduana { get; set; }
        public Nullable<decimal> PorcGastos { get; set; }
        public Nullable<decimal> IGI { get; set; }
        public Nullable<System.DateTime> FechaEntregaD { get; set; }
        public string ArticuloCore { get; set; }
        public Nullable<decimal> CostoCore { get; set; }
        public Nullable<decimal> CostoArt { get; set; }
        public Nullable<decimal> CostoRX { get; set; }
        public Nullable<decimal> DescImporte { get; set; }
        public string Descripcion2 { get; set; }
        public string DescuentoAplicado { get; set; }
        public Nullable<int> CompraID { get; set; }
        public Nullable<int> CompraRenglonID { get; set; }
        public string ObservacionesD { get; set; }
        public string CausaDevolucionD { get; set; }
        public Nullable<System.DateTime> FechaFacturaD { get; set; }
        public string NoFacturaD { get; set; }
        public string NoPedidoD { get; set; }
        public string PasoProduccion { get; set; }
        public string SPECUnidad { get; set; }
        public Nullable<decimal> TotalD { get; set; }
        public string UbicacionD { get; set; }
        public string SpecCarroceria { get; set; }
        public string Vin { get; set; }
        public string ArticuloVin { get; set; }
        public Nullable<int> SucursalD { get; set; }
    
        public virtual articulo articulo1 { get; set; }
        public virtual contacto contacto { get; set; }
    }
}
