//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cggasto
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public string ConceptoGasto { get; set; }
        public string ContactoGasto { get; set; }
        public decimal ImporteGasto { get; set; }
        public Nullable<decimal> ImpuestosGasto { get; set; }
        public Nullable<decimal> RetencionISRGasto { get; set; }
        public Nullable<decimal> RetencionIVAGasto { get; set; }
        public string MonedaGasto { get; set; }
        public decimal TipoCambioGasto { get; set; }
        public string Metodo { get; set; }
        public System.DateTime FechaEmisionGasto { get; set; }
        public string CondicionGasto { get; set; }
        public Nullable<System.DateTime> VencimientoGasto { get; set; }
        public string ReferenciaGasto { get; set; }
        public string Pedimento { get; set; }
        public string MovOrigen { get; set; }
    
        public virtual contacto contacto { get; set; }
    }
}
