//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cgimportacion
    {
        public int ID { get; set; }
        public string Documento { get; set; }
        public Nullable<System.DateTime> DocumentoFecha { get; set; }
        public string Guia { get; set; }
        public Nullable<System.DateTime> GuiaFecha { get; set; }
        public string Convenio { get; set; }
        public Nullable<int> Paquetes { get; set; }
        public string AgenteAduanal { get; set; }
        public string PuertoCarga { get; set; }
        public Nullable<System.DateTime> FechaCarga { get; set; }
        public string PuertoDestino { get; set; }
        public Nullable<System.DateTime> FechaDestino { get; set; }
    }
}
