//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cgmatfaltante
    {
        public int ID { get; set; }
        public int RenglonIDM { get; set; }
        public string Articulo { get; set; }
        public string Unidad { get; set; }
        public Nullable<decimal> CantidadPendiente { get; set; }
        public string Almacen { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Disponible { get; set; }
        public string Rankinghc { get; set; }
        public string TipoDem { get; set; }
        public Nullable<int> Messin { get; set; }
        public Nullable<decimal> CantidadSeleccion { get; set; }
    }
}
