//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cgmatfaltante1
    {
        public int ID { get; set; }
        public int RenglonIDM { get; set; }
        public string Articulo { get; set; }
        public string Unidad { get; set; }
        public Nullable<decimal> CantidadPendiente { get; set; }
        public string ArticuloSustituto { get; set; }
        public string ProveedorS { get; set; }
        public string NombreProveedorS { get; set; }
        public Nullable<decimal> CantidadSelecSust { get; set; }
    }
}
