//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cgordengastoid
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public string ContactoD { get; set; }
        public string Articulo { get; set; }
        public Nullable<decimal> CantidadUnidad { get; set; }
        public string Unidad { get; set; }
        public float Factor { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public decimal Impuesto1 { get; set; }
        public Nullable<decimal> Impuesto2 { get; set; }
        public string CentroCostosD { get; set; }
        public Nullable<decimal> CostoRX { get; set; }
        public string Vin { get; set; }
        public string ArticuloVin { get; set; }
        public string Descripcion2 { get; set; }
    }
}
