//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class citaspuente
    {
        public int ID { get; set; }
        public string Contacto { get; set; }
        public string Periodo { get; set; }
        public string Agente { get; set; }
        public int CantCitas { get; set; }
        public string Dias { get; set; }
        public Nullable<int> DiaSemana { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public string HoraInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string HoraFin { get; set; }
        public int CitasXDia { get; set; }
        public int HorasXCitas { get; set; }
        public string Asunto { get; set; }
        public string Objetivo { get; set; }
        public string Nombrecontacto { get; set; }
    }
}
