//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmsd
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public Nullable<int> AplicaID { get; set; }
        public string AgenteD { get; set; }
        public Nullable<decimal> ImporteComision { get; set; }
        public Nullable<decimal> ImpuestosD { get; set; }
        public Nullable<decimal> ImpuestoImporte { get; set; }
        public Nullable<decimal> RetencionesD { get; set; }
        public Nullable<decimal> ImpuestoRetencion { get; set; }
        public Nullable<decimal> ComisionAplicada { get; set; }
        public string MovCobro { get; set; }
        public Nullable<decimal> ImporteCobro { get; set; }
        public Nullable<System.DateTime> FechaCobro { get; set; }
        public string Factura { get; set; }
        public string Contacto { get; set; }
        public Nullable<decimal> MontoFactura { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string CondicionPago { get; set; }
        public Nullable<int> DiasTranscurridos { get; set; }
        public Nullable<decimal> AplicaAl { get; set; }
        public string ConceptoComision { get; set; }
    }
}
