//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmsmantto
    {
        public string CodigoCMS { get; set; }
        public string MantenimientoTipo { get; set; }
        public string Servicio { get; set; }
        public Nullable<decimal> ComisionxHrMO { get; set; }
        public Nullable<decimal> IyTFH { get; set; }
        public Nullable<decimal> IFHyTDH { get; set; }
        public Nullable<decimal> IDHyTFH { get; set; }
        public Nullable<int> MinHrMO { get; set; }
        public Nullable<decimal> ComisionxHrMo2 { get; set; }
    }
}
