//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmstipoct
    {
        public string CodigoCMS { get; set; }
        public string TipoContratoCT { get; set; }
        public Nullable<decimal> ImporteComisionCT { get; set; }
        public Nullable<decimal> ImporteComisionUnidad { get; set; }
    }
}
