//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class codigobarra
    {
        public string Codigo { get; set; }
        public string Tipo { get; set; }
        public string Cuenta { get; set; }
        public string Estandard { get; set; }
        public string SerieLote { get; set; }
        public string Unidad { get; set; }
    }
}
