//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class codigobarrasformula
    {
        public int ID { get; set; }
        public string Opc1 { get; set; }
        public string Opc2 { get; set; }
        public string Opc3 { get; set; }
        public string Opc4 { get; set; }
        public string Opc5 { get; set; }
        public string Opc6 { get; set; }
        public string Opc7 { get; set; }
        public string Opc8 { get; set; }
        public string Opc9 { get; set; }
    }
}
