//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comandad
    {
        public int Ubicacion { get; set; }
        public int Mesa { get; set; }
        public int RenglonID { get; set; }
        public int Persona { get; set; }
        public string Observaciones { get; set; }
        public string Estado { get; set; }
        public string Cocinero { get; set; }
        public Nullable<System.DateTime> FechaInicial { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<int> KitRenglonID { get; set; }
        public Nullable<int> RenglonControl { get; set; }
    }
}
