//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compiteviatico
    {
        public int ID { get; set; }
        public int Empresa { get; set; }
        public string Mov { get; set; }
        public int Sucursal { get; set; }
        public string Folio { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string Contacto { get; set; }
        public string CentroCostos { get; set; }
        public string Estado { get; set; }
        public string CodigoPostal { get; set; }
        public string Opcional1 { get; set; }
        public string Opcional2 { get; set; }
        public System.DateTime FechaInicioViaje { get; set; }
        public System.DateTime FechaFinViaje { get; set; }
        public int CantidadTerrestre { get; set; }
        public int CantidadPrimaHonorario { get; set; }
        public int CantidadPrimaHonorarioHosp { get; set; }
        public int CantidadNocheAdicional { get; set; }
        public int CantidadEstanciaProlongada { get; set; }
        public int CantidadTaller4 { get; set; }
        public int CantidadTaller2 { get; set; }
        public Nullable<bool> TieneImporteVariable { get; set; }
        public Nullable<decimal> ImporteVariable { get; set; }
        public string VueloDestino1 { get; set; }
        public Nullable<System.DateTime> VueloFecha1 { get; set; }
        public string Vuelo1 { get; set; }
        public Nullable<System.TimeSpan> VueloHoraSalida1 { get; set; }
        public Nullable<System.TimeSpan> VueloHoraArribo1 { get; set; }
        public string VueloLinea1 { get; set; }
        public string ClaveBoleto1 { get; set; }
        public Nullable<decimal> PrecioBoleto1 { get; set; }
        public string VueloDestino2 { get; set; }
        public Nullable<System.DateTime> VueloFecha2 { get; set; }
        public string Vuelo2 { get; set; }
        public Nullable<System.TimeSpan> VueloHoraSalida2 { get; set; }
        public Nullable<System.TimeSpan> VueloHoraArribo2 { get; set; }
        public string VueloLinea2 { get; set; }
        public string ClaveBoleto2 { get; set; }
        public Nullable<decimal> PrecioBoleto2 { get; set; }
        public string VueloDestino3 { get; set; }
        public Nullable<System.DateTime> VueloFecha3 { get; set; }
        public string Vuelo3 { get; set; }
        public Nullable<System.TimeSpan> VueloHoraSalida3 { get; set; }
        public Nullable<System.TimeSpan> VueloHoraArribo3 { get; set; }
        public string VueloLinea3 { get; set; }
        public string ClaveBoleto3 { get; set; }
        public Nullable<decimal> PrecioBoleto3 { get; set; }
        public string VueloDestino4 { get; set; }
        public Nullable<System.DateTime> VueloFecha4 { get; set; }
        public string Vuelo4 { get; set; }
        public Nullable<System.TimeSpan> VueloHoraSalida4 { get; set; }
        public Nullable<System.TimeSpan> VueloHoraArribo4 { get; set; }
        public string VueloLinea4 { get; set; }
        public string ClaveBoleto4 { get; set; }
        public Nullable<decimal> PrecioBoleto4 { get; set; }
        public string Usuario { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<double> RetencionIVA { get; set; }
        public Nullable<double> RetencionISR { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Comentarios { get; set; }
        public string Estatus { get; set; }
    
        public virtual contacto contacto1 { get; set; }
    }
}
