//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compitetarifazona
    {
        public string Zona { get; set; }
        public Nullable<decimal> TransporteTerrestre { get; set; }
        public Nullable<decimal> PrimaHonorarios { get; set; }
        public Nullable<decimal> PrimaHonorariosHosp { get; set; }
        public Nullable<decimal> NocheAdicional { get; set; }
        public Nullable<decimal> EstanciaProl { get; set; }
        public Nullable<decimal> Taller4Dias { get; set; }
        public Nullable<decimal> Taller2Dias { get; set; }
    }
}
