//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compiteotrosd
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public string CentroCostos { get; set; }
        public string Observaciones { get; set; }
        public decimal Porcentaje { get; set; }
        public decimal ImporteD { get; set; }
    }
}
