//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class concepto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public concepto()
        {
            this.conceptomovs = new HashSet<conceptomov>();
        }
    
        public string Modulo { get; set; }
        public string Concepto1 { get; set; }
        public Nullable<decimal> Impuestos { get; set; }
        public Nullable<decimal> RetencionISR { get; set; }
        public Nullable<decimal> RetencionIVA { get; set; }
        public string ContCuenta { get; set; }
        public bool DiotExcluir { get; set; }
        public bool Impuesto1Exento { get; set; }
        public bool DiotSumaValorAduana { get; set; }
        public string CentroCostos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conceptomov> conceptomovs { get; set; }
    }
}
