//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class constructor
    {
        public long ID { get; set; }
        public string Objeto { get; set; }
        public int Version { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
        public string SQLSCRIPT { get; set; }
        public string Empresa { get; set; }
        public string Tipo { get; set; }
        public bool Actualizar { get; set; }
        public Nullable<System.DateTime> UltimoCambio { get; set; }
    }
}
