//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactonominacuenta
    {
        public string Contacto { get; set; }
        public int NominaID { get; set; }
        public string NominaClave { get; set; }
        public string ContCuenta { get; set; }
    
        public virtual contacto contacto1 { get; set; }
        public virtual contcuenta contcuenta1 { get; set; }
        public virtual nominacalcd nominacalcd { get; set; }
    }
}
