//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactopersonal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contactopersonal()
        {
            this.contactobeneficiarios = new HashSet<contactobeneficiario>();
        }
    
        public string ContactoPersonal1 { get; set; }
        public string PersonalEstatus { get; set; }
        public string JefeInmediato { get; set; }
        public Nullable<int> PersonalSucursal { get; set; }
        public string NivelAcademico { get; set; }
        public Nullable<System.DateTime> FechaAntiguedad { get; set; }
        public string Genero { get; set; }
        public string EstadoCivil { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public Nullable<System.DateTime> FechaUltimoPago { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public string Departamento { get; set; }
        public string Puesto { get; set; }
        public string PersonalCategoria { get; set; }
        public string MovNomina { get; set; }
        public string ZonaEconomica { get; set; }
        public string Periodo { get; set; }
        public string Jornada { get; set; }
        public string ContratoTipo { get; set; }
        public Nullable<System.DateTime> ContratoVencimiento { get; set; }
        public Nullable<decimal> SueldoDiario { get; set; }
        public Nullable<decimal> SDI { get; set; }
        public string PersonalFormaPago { get; set; }
        public string PersonalNumCtaBancaria { get; set; }
        public string PersonalCuentaBanco { get; set; }
        public string PersonalMoneda { get; set; }
        public Nullable<int> Empresa { get; set; }
        public string TipoDias { get; set; }
        public string CentroCostos { get; set; }
        public string NSS { get; set; }
        public string TipoSueldo { get; set; }
        public Nullable<decimal> SDIAnterior { get; set; }
        public string Sindicalizado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contactobeneficiario> contactobeneficiarios { get; set; }
    }
}
