//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactoflota
    {
        public string Contacto { get; set; }
        public Nullable<int> TractosCantidad { get; set; }
        public Nullable<int> RTractosMCantidad { get; set; }
        public Nullable<int> LigerosCantidad { get; set; }
        public Nullable<int> SeveroCantidad { get; set; }
        public Nullable<int> PasajeCantidad { get; set; }
        public Nullable<int> TractosCantidadCR { get; set; }
        public Nullable<int> RTractosMCantidadCR { get; set; }
        public Nullable<int> LigerosCantidadCR { get; set; }
        public Nullable<int> SeveroCantidadCR { get; set; }
        public Nullable<int> PasajeCantidadCR { get; set; }
    }
}
