//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactodatoslegale
    {
        public string Contacto { get; set; }
        public string RepresentanteLegal { get; set; }
        public string EscrituraPublica { get; set; }
        public System.DateTime FechaConstitucion { get; set; }
        public string NombreNotarioPublico { get; set; }
        public int NumeroNotaria { get; set; }
        public string NoRegistroMercantil { get; set; }
        public string NoRegistroPatronalIMSS { get; set; }
        public string NoSeguridadPrivada { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
    }
}
