//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contgenerarlogd
    {
        public int ID { get; set; }
        public int IDInterno { get; set; }
        public string Modulo { get; set; }
        public Nullable<int> ModuloID { get; set; }
        public string Mov { get; set; }
        public string Folio { get; set; }
        public string Error { get; set; }
        public Nullable<int> PolizaID { get; set; }
        public string PolizaMov { get; set; }
        public string PolizaFolio { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
    }
}
