//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contgenerard
    {
        public string Modulo { get; set; }
        public string Mov { get; set; }
        public string Nombre { get; set; }
        public string Cuenta { get; set; }
        public string CuentaFija { get; set; }
        public Nullable<bool> LlevaCentroCostos { get; set; }
        public string CentroCostos { get; set; }
        public string Cargo { get; set; }
        public string Abono { get; set; }
        public bool Cuadre { get; set; }
        public bool Agrupar { get; set; }
    }
}
