//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactoproveedor
    {
        public string Contacto { get; set; }
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string Extension { get; set; }
        public string Email { get; set; }
        public string Puesto { get; set; }
        public string Licencia { get; set; }
        public Nullable<System.DateTime> Vigencia { get; set; }
        public string TipoLicencia { get; set; }
        public string Clasificacion { get; set; }
        public string Direccion { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
    
        public virtual contacto contacto1 { get; set; }
    }
}
