//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class correoadjunto
    {
        public string Modulo { get; set; }
        public int ID { get; set; }
        public int IDInterno { get; set; }
        public string ArchivoAdjunto { get; set; }
        public Nullable<bool> Adjuntar { get; set; }
        public int RenglonIDInterno { get; set; }
    }
}
