//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class correo
    {
        public int ID { get; set; }
        public string Modulo { get; set; }
        public string Asunto { get; set; }
        public string Cuerpo { get; set; }
        public Nullable<bool> Espanol { get; set; }
        public Nullable<bool> Ingles { get; set; }
        public string Email { get; set; }
        public string Usuario { get; set; }
    }
}
