//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm
    {
        public int ID { get; set; }
        public int Empresa { get; set; }
        public string Mov { get; set; }
        public int Sucursal { get; set; }
        public string Folio { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string Proyecto { get; set; }
        public string Usuario { get; set; }
        public string Estatus { get; set; }
        public string NivelInteres { get; set; }
        public int Plantilla { get; set; }
        public bool EsCto { get; set; }
        public string Contacto { get; set; }
        public Nullable<int> Propuesta { get; set; }
        public Nullable<System.DateTime> FechaConclusion { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public string Medio { get; set; }
        public string SubMedio { get; set; }
        public string WFEstado { get; set; }
        public string WFUsuario { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string Vendedor { get; set; }
        public string ClientePrimarioC { get; set; }
        public string GrupoClienteC { get; set; }
        public string SubGrupoClienteC { get; set; }
        public string ObservacionesE { get; set; }
        public string Prioridad { get; set; }
        public string GrupoContrato { get; set; }
        public string Objecion1 { get; set; }
        public string Objecion2 { get; set; }
        public string Concepto { get; set; }
    
        public virtual crmplantilla crmplantilla { get; set; }
    }
}
