//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmcotizadorunidad
    {
        public int ID { get; set; }
        public int Propuesta { get; set; }
        public int RenglonID { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> ModeloAno { get; set; }
        public Nullable<decimal> CostoChasis { get; set; }
        public string Proveedorc { get; set; }
        public string Carroceria { get; set; }
        public Nullable<decimal> CostoCarroceria { get; set; }
        public string Motor { get; set; }
        public string Torque { get; set; }
        public string Embrague { get; set; }
        public string Transmision { get; set; }
        public string EjeDelantero { get; set; }
        public string EjeTrasero { get; set; }
        public string SuspDelantera { get; set; }
        public string SuspTrasera { get; set; }
        public string Llantas { get; set; }
        public string Tanques { get; set; }
        public string Direccion { get; set; }
        public string Frenos { get; set; }
        public string Bastidor { get; set; }
        public string Camarote { get; set; }
        public string PBVPBC { get; set; }
        public string Ejes { get; set; }
        public string Configuracion { get; set; }
        public string SpecCarroceria { get; set; }
        public string Cabina { get; set; }
        public Nullable<int> ReglaAplicaUn { get; set; }
        public string CostoAplicaUn { get; set; }
        public Nullable<int> ClaseModelo { get; set; }
    }
}
