//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmcontacto
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public string Direccion { get; set; }
        public string NumeroExterior { get; set; }
        public string NumeroInterior { get; set; }
        public string Colonia { get; set; }
        public string Poblacion { get; set; }
        public string Estado { get; set; }
        public string CodigoPostal { get; set; }
        public string Telefonos { get; set; }
        public string Fax { get; set; }
        public string Grupo { get; set; }
        public string Pais { get; set; }
        public string RegimenFiscal { get; set; }
        public string Email { get; set; }
        public string ClientePrimario { get; set; }
        public string GrupoCliente { get; set; }
        public string SubGrupoCliente { get; set; }
        public string Subgrupo { get; set; }
        public string NombreComercial { get; set; }
        public string PagWeb { get; set; }
        public string UsoComprobante { get; set; }
        public string Zona { get; set; }
        public Nullable<bool> idealnet { get; set; }
    }
}
