//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmcotizadorcreditoextd
    {
        public int ID { get; set; }
        public int Propuesta { get; set; }
        public int RenglonID { get; set; }
        public Nullable<decimal> PorcEnganche { get; set; }
        public Nullable<decimal> RentaEnDeposito { get; set; }
        public Nullable<decimal> ComisionAperturaCIVA { get; set; }
        public Nullable<decimal> GastosContratacionCIVA { get; set; }
        public Nullable<decimal> AbonoACapital { get; set; }
        public Nullable<decimal> PagoInicial1 { get; set; }
        public Nullable<decimal> PagoDuranteGracia { get; set; }
        public Nullable<decimal> PagoMensual { get; set; }
        public Nullable<decimal> MontoFinanciamiento { get; set; }
        public Nullable<decimal> OpcionCompra { get; set; }
        public Nullable<decimal> PorcEnganche12 { get; set; }
        public Nullable<decimal> RentaEnDeposito12 { get; set; }
        public Nullable<decimal> ComisionAperturaCIVA12 { get; set; }
        public Nullable<decimal> GastosContratacionCIVA12 { get; set; }
        public Nullable<decimal> AbonoACapital12 { get; set; }
        public Nullable<decimal> PagoInicial12 { get; set; }
        public Nullable<decimal> PagoDuranteGracia12 { get; set; }
        public Nullable<decimal> PagoMensual12 { get; set; }
        public Nullable<decimal> MontoFinanciamiento12 { get; set; }
        public Nullable<decimal> OpcionCompra12 { get; set; }
        public Nullable<decimal> PorcEnganche24 { get; set; }
        public Nullable<decimal> RentaEnDeposito24 { get; set; }
        public Nullable<decimal> ComisionAperturaCIVA24 { get; set; }
        public Nullable<decimal> GastosContratacionCIVA24 { get; set; }
        public Nullable<decimal> AbonoACapital24 { get; set; }
        public Nullable<decimal> PagoInicial24 { get; set; }
        public Nullable<decimal> PagoDuranteGracia24 { get; set; }
        public Nullable<decimal> PagoMensual24 { get; set; }
        public Nullable<decimal> MontoFinanciamiento24 { get; set; }
        public Nullable<decimal> OpcionCompra24 { get; set; }
        public Nullable<decimal> PorcEnganche36 { get; set; }
        public Nullable<decimal> RentaEnDeposito36 { get; set; }
        public Nullable<decimal> ComisionAperturaCIVA36 { get; set; }
        public Nullable<decimal> GastosContratacionCIVA36 { get; set; }
        public Nullable<decimal> AbonoACapital36 { get; set; }
        public Nullable<decimal> PagoInicial36 { get; set; }
        public Nullable<decimal> PagoDuranteGracia36 { get; set; }
        public Nullable<decimal> PagoMensual36 { get; set; }
        public Nullable<decimal> MontoFinanciamiento36 { get; set; }
        public Nullable<decimal> OpcionCompra36 { get; set; }
        public Nullable<decimal> PorcEnganche48 { get; set; }
        public Nullable<decimal> RentaEnDeposito48 { get; set; }
        public Nullable<decimal> ComisionAperturaCIVA48 { get; set; }
        public Nullable<decimal> GastosContratacionCIVA48 { get; set; }
        public Nullable<decimal> AbonoACapital48 { get; set; }
        public Nullable<decimal> PagoInicial48 { get; set; }
        public Nullable<decimal> PagoDuranteGracia48 { get; set; }
        public Nullable<decimal> PagoMensual48 { get; set; }
        public Nullable<decimal> MontoFinanciamiento48 { get; set; }
        public Nullable<decimal> OpcionCompra48 { get; set; }
        public Nullable<decimal> PorcEnganche60 { get; set; }
        public Nullable<decimal> RentaEnDeposito60 { get; set; }
        public Nullable<decimal> ComisionAperturaCIVA60 { get; set; }
        public Nullable<decimal> GastosContratacionCIVA60 { get; set; }
        public Nullable<decimal> AbonoACapital60 { get; set; }
        public Nullable<decimal> PagoInicial60 { get; set; }
        public Nullable<decimal> PagoDuranteGracia60 { get; set; }
        public Nullable<decimal> PagoMensual60 { get; set; }
        public Nullable<decimal> MontoFinanciamiento60 { get; set; }
        public Nullable<decimal> OpcionCompra60 { get; set; }
        public Nullable<decimal> PorcEnganche72 { get; set; }
        public Nullable<decimal> RentaEnDeposito72 { get; set; }
        public Nullable<decimal> ComisionAperturaCIVA72 { get; set; }
        public Nullable<decimal> GastosContratacionCIVA72 { get; set; }
        public Nullable<decimal> AbonoACapital72 { get; set; }
        public Nullable<decimal> PagoInicial72 { get; set; }
        public Nullable<decimal> PagoDuranteGracia72 { get; set; }
        public Nullable<decimal> PagoMensual72 { get; set; }
        public Nullable<decimal> MontoFinanciamiento72 { get; set; }
        public Nullable<decimal> OpcionCompra72 { get; set; }
        public Nullable<int> PlazoCalcular { get; set; }
        public Nullable<int> PlazoCalcular12 { get; set; }
        public Nullable<int> PlazoCalcular24 { get; set; }
        public Nullable<int> PlazoCalcular36 { get; set; }
        public Nullable<int> PlazoCalcular48 { get; set; }
        public Nullable<int> PlazoCalcular60 { get; set; }
        public Nullable<int> PlazoCalcular72 { get; set; }
        public Nullable<decimal> ValorCamionFinanciado { get; set; }
    }
}
