//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmcampanaunidad
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public string Tipo { get; set; }
        public string Modelo { get; set; }
        public string Ano { get; set; }
        public string Marca { get; set; }
        public string Serie { get; set; }
        public string KM { get; set; }
    }
}
