//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmcotizadorcompcard
    {
        public int ID { get; set; }
        public int Propuesta { get; set; }
        public int RenglonID { get; set; }
        public int IDInterno { get; set; }
        public string ArticuloA { get; set; }
        public string Descripcion2A { get; set; }
        public decimal CantidadUnidadA { get; set; }
        public string MonedaA { get; set; }
        public decimal CostoA { get; set; }
        public Nullable<bool> FacturacionA { get; set; }
        public string UnidadA { get; set; }
        public Nullable<bool> Incluido { get; set; }
        public Nullable<bool> CobrarA { get; set; }
    }
}
