//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmcotizadorcreditoext
    {
        public int ID { get; set; }
        public int Propuesta { get; set; }
        public int RenglonID { get; set; }
        public string TipoCredito { get; set; }
        public string MonedaFinanciamiento { get; set; }
        public Nullable<decimal> PagoInicial { get; set; }
        public Nullable<int> MesesGracia { get; set; }
        public Nullable<decimal> PrecioVentaCreDLS { get; set; }
        public Nullable<decimal> PrecioVentaCrePesos { get; set; }
        public Nullable<decimal> TCVentaCredito { get; set; }
        public Nullable<decimal> SubsidioTCVenta { get; set; }
        public Nullable<decimal> TCVtaNeto { get; set; }
        public Nullable<bool> ImpCotiz12 { get; set; }
        public Nullable<bool> ImpCotiz24 { get; set; }
        public Nullable<bool> ImpCotiz36 { get; set; }
        public Nullable<bool> ImpCotiz48 { get; set; }
        public Nullable<bool> ImpCotiz60 { get; set; }
        public Nullable<bool> ImpCotiz72 { get; set; }
        public Nullable<bool> ImpCotiztabla12 { get; set; }
        public Nullable<bool> ImpCotiztabla24 { get; set; }
        public Nullable<bool> ImpCotiztabla36 { get; set; }
        public Nullable<bool> ImpCotiztabla48 { get; set; }
        public Nullable<bool> ImpCotiztabla60 { get; set; }
        public Nullable<bool> ImpCotiztabla72 { get; set; }
        public Nullable<decimal> PagoInicialImporte { get; set; }
        public Nullable<int> RentaAnticipadas { get; set; }
        public Nullable<decimal> RentaAnticipadasImp { get; set; }
    }
}
