//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmcotizadorcompcar
    {
        public int ID { get; set; }
        public int Propuesta { get; set; }
        public int RenglonID { get; set; }
        public Nullable<decimal> TotalCostoCCPesos { get; set; }
        public Nullable<decimal> TotalCostoCCDolares { get; set; }
        public Nullable<decimal> TotalCCPesos { get; set; }
        public string AccesoriosCarroceria { get; set; }
        public Nullable<decimal> InyectableAct { get; set; }
        public Nullable<decimal> InyectableTelaAct { get; set; }
        public Nullable<decimal> AltosTelaAct { get; set; }
        public Nullable<decimal> AltosReclinablesAct { get; set; }
        public Nullable<decimal> TropicalAct { get; set; }
        public Nullable<decimal> CantidadInyectableAct { get; set; }
        public Nullable<decimal> CantidadInyectableTelaAct { get; set; }
        public Nullable<decimal> CantidadAltosTelaAct { get; set; }
        public Nullable<decimal> CantidadAltosReclinablesAct { get; set; }
        public Nullable<decimal> CantidadTropicalAct { get; set; }
    }
}
