//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmcotizadorcreditointd
    {
        public int IDInterno { get; set; }
        public int ID { get; set; }
        public int Propuesta { get; set; }
        public int RenglonID { get; set; }
        public Nullable<int> NoPagosInt { get; set; }
        public Nullable<decimal> SaldoInt { get; set; }
        public Nullable<decimal> CapitalInt { get; set; }
        public Nullable<decimal> InteresesInt { get; set; }
        public Nullable<decimal> IVAInteresInt { get; set; }
        public Nullable<decimal> PagoTotalInt { get; set; }
    }
}
