//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmcotizadorcreditoint
    {
        public int ID { get; set; }
        public int Propuesta { get; set; }
        public int RenglonID { get; set; }
        public string TipoCreditoInt { get; set; }
        public string MonedaFinancInt { get; set; }
        public Nullable<decimal> PrecioVentaCreInt { get; set; }
        public Nullable<decimal> PorcPagoInicialInt { get; set; }
        public Nullable<decimal> PorcPagoInicial2int { get; set; }
        public Nullable<int> PagosCredInt { get; set; }
        public Nullable<int> DiasCPagoint { get; set; }
        public Nullable<int> PLazoDiasint { get; set; }
        public Nullable<decimal> TasaAnualint { get; set; }
        public Nullable<decimal> RentaDepositoInt { get; set; }
        public Nullable<decimal> ComisionPorcint { get; set; }
        public Nullable<decimal> GastosContratacionInt { get; set; }
        public Nullable<decimal> MontoFinanciamientoInt { get; set; }
        public Nullable<decimal> PagoInt { get; set; }
        public Nullable<decimal> RentaDepositoIntImp { get; set; }
        public Nullable<decimal> ComisionIntImporte { get; set; }
        public Nullable<decimal> TotalCapitalInt { get; set; }
        public Nullable<decimal> TotalInteresesInt { get; set; }
        public Nullable<decimal> TotalIVAInteresInt { get; set; }
        public Nullable<decimal> TotalPagoInt { get; set; }
        public Nullable<decimal> PrecioVentaCredIntDLS { get; set; }
    }
}
