//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmd
    {
        public int ID { get; set; }
        public int Orden { get; set; }
        public string Tema { get; set; }
        public decimal Numero { get; set; }
        public string Actividad { get; set; }
        public string ContactoD { get; set; }
        public Nullable<decimal> Avance { get; set; }
        public string ObservacionesD { get; set; }
        public Nullable<bool> EnProceso { get; set; }
        public Nullable<bool> Concluido { get; set; }
        public string FechaConclusionA { get; set; }
        public int RenglonID { get; set; }
    }
}
