//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmoperacione
    {
        public int ID { get; set; }
        public string RutaOperacion { get; set; }
        public Nullable<int> NoEmpleados { get; set; }
        public Nullable<decimal> kmMes { get; set; }
        public string DescripcionGralNegocio { get; set; }
        public string Comentarios { get; set; }
        public string DescripcionInst { get; set; }
        public string DescripcionControlNeg { get; set; }
    }
}
