//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmpresupcopiar
    {
        public string PID { get; set; }
        public Nullable<bool> Enero { get; set; }
        public Nullable<bool> Febrero { get; set; }
        public Nullable<bool> Marzo { get; set; }
        public Nullable<bool> Abril { get; set; }
        public Nullable<bool> Mayo { get; set; }
        public Nullable<bool> Junio { get; set; }
        public Nullable<bool> Julio { get; set; }
        public Nullable<bool> Agosto { get; set; }
        public Nullable<bool> Septiembre { get; set; }
        public Nullable<bool> Octubre { get; set; }
        public Nullable<bool> Noviembre { get; set; }
        public Nullable<bool> Diciembre { get; set; }
    }
}
