//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmsegmentacion
    {
        public int ID { get; set; }
        public string TipoCliente { get; set; }
        public string SectorCliente { get; set; }
        public string TipoCarga { get; set; }
        public string TallerMantenimiento { get; set; }
        public Nullable<bool> idealnet { get; set; }
    }
}
