//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct
    {
        public int ID { get; set; }
        public int Empresa { get; set; }
        public string Mov { get; set; }
        public int Sucursal { get; set; }
        public string Folio { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string Usuario { get; set; }
        public string Estatus { get; set; }
        public string WFEstado { get; set; }
        public string WFUsuario { get; set; }
        public Nullable<System.DateTime> FechaConclusion { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public string Concepto { get; set; }
        public string Referencia { get; set; }
        public string Observaciones { get; set; }
        public string Proyecto { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> TipoCambio { get; set; }
        public string Contacto { get; set; }
        public string TipoContrato { get; set; }
        public Nullable<System.DateTime> FechaFirma { get; set; }
        public string CiudadFirma { get; set; }
        public string EstadoFirma { get; set; }
        public string PaisFirma { get; set; }
        public Nullable<System.DateTime> FechaInicioContrato { get; set; }
        public Nullable<System.DateTime> FechaFinContrato { get; set; }
        public string Periodo { get; set; }
        public Nullable<int> NumeroDocumentos { get; set; }
        public Nullable<decimal> ValorProyecto { get; set; }
        public Nullable<decimal> ImporteDocumentos { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> Impuestos { get; set; }
        public Nullable<decimal> Impuestos2 { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string ListaPrecios { get; set; }
        public string Testigo1 { get; set; }
        public string Testigo2 { get; set; }
        public string Afianzadora { get; set; }
        public Nullable<int> NoPoliza { get; set; }
        public string OrigenModulo { get; set; }
        public Nullable<int> OrigenID { get; set; }
        public string Contacto2 { get; set; }
        public Nullable<int> OrigenCTID { get; set; }
        public Nullable<decimal> PrecioUnidad { get; set; }
        public Nullable<decimal> PrecioComodato { get; set; }
    }
}
