//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctentregarecepab
    {
        public int ID { get; set; }
        public int IDUnidad { get; set; }
        public string Abuso { get; set; }
        public decimal Precio { get; set; }
        public string Moneda { get; set; }
        public Nullable<bool> Seleccionar { get; set; }
    }
}
