//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctentregarecper
    {
        public int ID { get; set; }
        public int IDUnidad { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string HoraEntrega { get; set; }
        public Nullable<int> HrRefrigerado { get; set; }
        public string Operador { get; set; }
        public string Licencia { get; set; }
        public string NivelGasolina { get; set; }
        public string NivelUrea { get; set; }
        public string NivelThermo { get; set; }
        public Nullable<int> KM { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public string HoraSalida { get; set; }
        public Nullable<int> HrRefrigeradoS { get; set; }
        public string OperadorS { get; set; }
        public string LicenciaS { get; set; }
        public string NivelGasolinaS { get; set; }
        public string NivelUreaS { get; set; }
        public string NivelThermoS { get; set; }
        public Nullable<int> KMS { get; set; }
    }
}
