//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctunidadcontrato
    {
        public int ID { get; set; }
        public int IDUnidad { get; set; }
        public string Tipo { get; set; }
        public string Modelo { get; set; }
        public string Ano { get; set; }
        public string Marca { get; set; }
        public string Serie { get; set; }
        public string Carroceria { get; set; }
        public string Color { get; set; }
        public string Placas { get; set; }
        public Nullable<System.DateTime> FechaInicial { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<decimal> CargoFijo { get; set; }
        public Nullable<decimal> CargoxKM { get; set; }
        public Nullable<decimal> CargoxHrRefri { get; set; }
        public Nullable<decimal> CargoxTelemetria { get; set; }
        public Nullable<decimal> KMaRecorrer { get; set; }
        public Nullable<decimal> KMIncluidos { get; set; }
        public Nullable<decimal> HrRefriMes { get; set; }
        public Nullable<decimal> HrRefriIncluidos { get; set; }
        public string PeriodoFactura { get; set; }
        public string PeriodoTotal { get; set; }
        public string DiaFactura { get; set; }
        public string ModeloFact { get; set; }
        public string Seguro { get; set; }
        public Nullable<System.DateTime> FechaExpira { get; set; }
        public string EstatusUnidad { get; set; }
        public string MonedaCargoxKm { get; set; }
        public string MonedaCargoxHrRefri { get; set; }
        public string NoEconomico { get; set; }
        public string MonedaCargoxTelemetria { get; set; }
        public Nullable<bool> Interno { get; set; }
        public string TipoCarroceria { get; set; }
        public string MonedaCargoF { get; set; }
    }
}
