//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentabanco
    {
        public string Clave { get; set; }
        public string Nombre { get; set; }
        public bool EsCaja { get; set; }
        public bool PermiteSobregiro { get; set; }
        public string NumeroCuenta { get; set; }
        public string Banco { get; set; }
        public string SucursalBancaria { get; set; }
        public int Empresa { get; set; }
        public string Moneda { get; set; }
        public bool Utilizado { get; set; }
        public string ContCuenta { get; set; }
        public bool CajaAbierta { get; set; }
        public int SucursalCuenta { get; set; }
        public Nullable<decimal> LimiteSaldo { get; set; }
        public string RFC { get; set; }
        public string Clabe { get; set; }
        public string SWIFCode { get; set; }
        public bool EsLineaCredito { get; set; }
        public string ContCuentaComplementaria { get; set; }
    }
}
