//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class embarquependiente
    {
        public int PID { get; set; }
        public bool Seleccionar { get; set; }
        public int ID { get; set; }
        public string Modulo { get; set; }
        public string Movimiento { get; set; }
        public string MovimientoFolio { get; set; }
        public int SucursalMov { get; set; }
        public System.DateTime FechaEmisionMov { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string ReferenciaMov { get; set; }
        public string CuentaMov { get; set; }
        public Nullable<int> ContactoEntrega { get; set; }
        public string CuentaNombre { get; set; }
        public string Colonia { get; set; }
        public string CodigoPostal { get; set; }
        public string Ruta { get; set; }
    }
}
