//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class embarque
    {
        public int ID { get; set; }
        public int Empresa { get; set; }
        public string Mov { get; set; }
        public int Sucursal { get; set; }
        public string Folio { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string Usuario { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> FechaConclusion { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public string Referencia { get; set; }
        public string Observaciones { get; set; }
        public string Concepto { get; set; }
        public string Proyecto { get; set; }
        public bool Externo { get; set; }
        public string Contacto { get; set; }
        public string Vehiculo { get; set; }
        public string Chofer { get; set; }
        public Nullable<decimal> Volumen { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<int> Bultos { get; set; }
        public Nullable<decimal> Cajas { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public string HoraSalida { get; set; }
        public Nullable<System.DateTime> FechaLlegada { get; set; }
        public string HoraLlegada { get; set; }
        public string WFEstado { get; set; }
        public string WFUsuario { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public string ClaseEmbarque { get; set; }
        public Nullable<int> DiasEmbarque { get; set; }
        public Nullable<System.DateTime> FechaMaxEntrega { get; set; }
    }
}
