//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class embarqueasignado
    {
        public Nullable<int> Orden { get; set; }
        public int IDEmbarqueMov { get; set; }
        public Nullable<int> IDAsignado { get; set; }
        public string MovimientoFolioAsignado { get; set; }
        public System.DateTime FechaEmisionAsignado { get; set; }
        public string ReferenciaAsignado { get; set; }
        public string CuentaAsignado { get; set; }
        public Nullable<int> ContactoEntregaAsignado { get; set; }
        public string CuentaNombreAsignado { get; set; }
        public string ColoniaAsignado { get; set; }
        public string CodigoPostalAsignado { get; set; }
        public string RutaAsignado { get; set; }
    }
}
