//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class embarqued
    {
        public int ID { get; set; }
        public int Renglon { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<int> EmbarqueMov { get; set; }
        public string EmbarqueEstado { get; set; }
        public string Motivo { get; set; }
        public string ReferenciaD { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<decimal> CajasD { get; set; }
    }
}
