//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresaconfiglista
    {
        public string Configuracion { get; set; }
        public string Modulo { get; set; }
        public string Valor { get; set; }
        public string Descripcion { get; set; }
        public bool EsNumero { get; set; }
        public bool EsEditable { get; set; }
    }
}
