//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        public int Empresa1 { get; set; }
        public string Nombre { get; set; }
        public string Estatus { get; set; }
        public string Direccion { get; set; }
        public string Colonia { get; set; }
        public string Poblacion { get; set; }
        public string Estado { get; set; }
        public string Codigopostal { get; set; }
        public string Pais { get; set; }
        public string Telefonos { get; set; }
        public string Fax { get; set; }
        public string PaginaWeb { get; set; }
        public string Grupo { get; set; }
        public bool Utilizado { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public string NumeroInterior { get; set; }
        public string NumeroExterior { get; set; }
        public string RegimenFiscal { get; set; }
        public string CFDIUsuarioPac { get; set; }
        public string CFDIURLPac { get; set; }
        public string CFDIPasswordPac { get; set; }
        public string CFDISoportePac { get; set; }
        public string CorreoServidorSaliente { get; set; }
        public Nullable<int> CorreoPuerto { get; set; }
        public Nullable<int> CorreoTipoAutenticacion { get; set; }
        public string CorreoCuentaUsuario { get; set; }
        public string CorreoPassword { get; set; }
        public string CorreoAsunto { get; set; }
        public string CorreoMensaje { get; set; }
        public string CorreoEmisor { get; set; }
        public string CorreoCifrado { get; set; }
        public string RegimenFiscalClave { get; set; }
        public string CFDIRfcProvCertif { get; set; }
        public string FERutaCertificado { get; set; }
        public string FERutaKey { get; set; }
        public string FEClaveLlave { get; set; }
        public string CorreoServidorSalienteNomina { get; set; }
        public Nullable<int> CorreoPuertoNomina { get; set; }
        public Nullable<int> CorreoTipoAutenticacionNomina { get; set; }
        public string CorreoCuentaUsuarioNomina { get; set; }
        public string CorreoPasswordNomina { get; set; }
        public string CorreoAsuntoNomina { get; set; }
        public string CorreoMensajeNomina { get; set; }
        public string CorreoEmisorNomina { get; set; }
        public string CorreoCifradoNomina { get; set; }
        public string LogoEmpresarialRuta { get; set; }
        public byte[] LogoEmpresarialImagen { get; set; }
        public string URLCancelacion { get; set; }
    }
}
