//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fcserie
    {
        public string Serie { get; set; }
        public string Tipo { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string Estatus { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public Nullable<int> IDBC { get; set; }
        public string Cliente { get; set; }
        public int Empresa { get; set; }
        public string Articulo { get; set; }
    }
}
