//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class formapagocobro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public formapagocobro()
        {
            this.fpcdenoms = new HashSet<fpcdenom>();
        }
    
        public string FormaPagoCobro1 { get; set; }
        public bool FlujoEfectivo { get; set; }
        public bool RequiereReferencia { get; set; }
        public bool PermiteCambio { get; set; }
        public bool PV { get; set; }
        public bool PinPad { get; set; }
        public string Moneda { get; set; }
        public string ContactoCxc { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> Orden { get; set; }
        public bool Denominacion { get; set; }
        public bool Fidelidad { get; set; }
        public string FidelidadTipo { get; set; }
        public string ClaveSat { get; set; }
        public bool Bancarizada { get; set; }
        public string OrdenanteRFC { get; set; }
        public bool OrdenanteCuenta { get; set; }
        public string BeneficiarioRFC { get; set; }
        public string BeneficiarioCuenta { get; set; }
        public string TipoCadenaPago { get; set; }
        public bool NumOperacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fpcdenom> fpcdenoms { get; set; }
    }
}
