//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class generadoretiqueta
    {
        public int IDInterno { get; set; }
        public int PID { get; set; }
        public int Empresa { get; set; }
        public string Modulo { get; set; }
        public string Mov { get; set; }
        public string Folio { get; set; }
        public string Almacen { get; set; }
        public string Articulo { get; set; }
        public string CodigoBarras { get; set; }
        public decimal Disponible { get; set; }
        public bool GeneraUnaEtiqueta { get; set; }
        public int Sucursal { get; set; }
    }
}
