//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icconfig
    {
        public int OCEmpresa { get; set; }
        public string OCContacto { get; set; }
        public string OCMoneda { get; set; }
        public int PedidoEmpresa { get; set; }
        public string PedidoContacto { get; set; }
        public string PedidoAlmacen { get; set; }
        public string PedidoListaPrecios { get; set; }
    }
}
