//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv
    {
        public int ID { get; set; }
        public int Empresa { get; set; }
        public string Mov { get; set; }
        public int Sucursal { get; set; }
        public string Folio { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string Usuario { get; set; }
        public string Moneda { get; set; }
        public decimal TipoCambio { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> FechaConclusion { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public string Referencia { get; set; }
        public string Observaciones { get; set; }
        public string Concepto { get; set; }
        public string Proyecto { get; set; }
        public string Almacen { get; set; }
        public string AlmacenDestino { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string OrigenModulo { get; set; }
        public Nullable<int> OrigenID { get; set; }
        public string CentroCostos { get; set; }
        public string WFEstado { get; set; }
        public string WFUsuario { get; set; }
        public Nullable<int> BultosTotal { get; set; }
        public bool Embarcar { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string EmbarqueEstado { get; set; }
        public Nullable<System.DateTime> FechaVenceMov { get; set; }
        public string Agente { get; set; }
        public Nullable<bool> ParteUnidad { get; set; }
        public string ArticuloParteUnidad { get; set; }
        public string SerieParte { get; set; }
        public string ubicacion { get; set; }
        public Nullable<System.DateTime> Vencimiento { get; set; }
        public bool Entregado { get; set; }
    
        public virtual almacen almacen1 { get; set; }
        public virtual almacen almacen2 { get; set; }
    }
}
