//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invd
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public string Articulo { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public decimal Costo { get; set; }
        public Nullable<int> AplicaID { get; set; }
        public Nullable<decimal> CantidadPendiente { get; set; }
        public Nullable<int> KitRenglonID { get; set; }
        public Nullable<int> RenglonControl { get; set; }
        public Nullable<decimal> CantidadA { get; set; }
        public Nullable<decimal> CantidadUnidad { get; set; }
        public string Unidad { get; set; }
        public float Factor { get; set; }
        public string ProdLote { get; set; }
        public string ProdArticulo { get; set; }
        public Nullable<int> Bultos { get; set; }
        public Nullable<decimal> CantidadEmbarcada { get; set; }
        public Nullable<decimal> CantidadReservada { get; set; }
        public string ConceptoD { get; set; }
        public string ObservacionesD { get; set; }
        public string AgenteD { get; set; }
        public string Descripcion2 { get; set; }
        public string Motivo { get; set; }
        public string UbicacionD { get; set; }
        public Nullable<int> IDSolicOrigen { get; set; }
    
        public virtual articulo articulo1 { get; set; }
    }
}
