//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invmodulotransfrastreo
    {
        public int ID { get; set; }
        public string OModulo { get; set; }
        public int OID { get; set; }
        public int ORenglonID { get; set; }
        public string DModulo { get; set; }
        public int DID { get; set; }
        public bool Cancelado { get; set; }
    }
}
