//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invnivelsurtidod
    {
        public int PID { get; set; }
        public int ID { get; set; }
        public string Linea { get; set; }
        public string SubLinea { get; set; }
        public string Marca { get; set; }
        public string Articulo { get; set; }
        public string Mov { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> ImporteCosto { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> ImportePrecio { get; set; }
        public string TipDem { get; set; }
        public string RankingHC { get; set; }
        public string MesesSinHit { get; set; }
        public Nullable<decimal> Surtido { get; set; }
        public Nullable<decimal> PorRecibir { get; set; }
        public Nullable<decimal> PorSurtir { get; set; }
    }
}
