//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invplanformulafactor
    {
        public int Clave { get; set; }
        public int MesAnterior { get; set; }
        public Nullable<decimal> Peso { get; set; }
    
        public virtual invplanformula invplanformula { get; set; }
    }
}
