//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invpland
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public Nullable<int> AplicaID { get; set; }
        public Nullable<System.DateTime> FechaInicioD { get; set; }
        public Nullable<System.DateTime> FechaFinD { get; set; }
        public Nullable<int> CantidadDias { get; set; }
        public Nullable<int> CantidadArticulosD { get; set; }
        public string AgenteEncargado { get; set; }
        public string ArticuloD { get; set; }
        public Nullable<System.DateTime> FechaDInv { get; set; }
        public Nullable<int> NoMovimiento { get; set; }
    }
}
