//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invplansugerido
    {
        public int PID { get; set; }
        public string Almacen { get; set; }
        public string Articulo { get; set; }
        public string Unidad { get; set; }
        public string TipoDemanda { get; set; }
        public Nullable<decimal> PorRecibir { get; set; }
        public Nullable<decimal> PorSurtir { get; set; }
        public Nullable<decimal> Disponible { get; set; }
        public Nullable<decimal> DisponibleNeto { get; set; }
        public Nullable<decimal> Minimo { get; set; }
        public Nullable<decimal> Maximo { get; set; }
        public Nullable<decimal> Requerimiento { get; set; }
        public Nullable<decimal> Ordenar { get; set; }
        public Nullable<decimal> Sugerido { get; set; }
        public string Proveedor { get; set; }
        public Nullable<int> M1 { get; set; }
        public Nullable<int> M2 { get; set; }
        public Nullable<int> M3 { get; set; }
        public Nullable<int> M4 { get; set; }
        public Nullable<int> M5 { get; set; }
        public Nullable<int> M6 { get; set; }
        public Nullable<int> M7 { get; set; }
        public Nullable<int> M8 { get; set; }
        public Nullable<int> M9 { get; set; }
        public Nullable<int> M10 { get; set; }
        public Nullable<int> M11 { get; set; }
        public Nullable<int> M12 { get; set; }
        public Nullable<decimal> MS1 { get; set; }
        public Nullable<decimal> MS2 { get; set; }
        public Nullable<decimal> MS3 { get; set; }
        public Nullable<decimal> MS4 { get; set; }
        public Nullable<decimal> MS5 { get; set; }
        public Nullable<decimal> MS6 { get; set; }
        public Nullable<decimal> MS7 { get; set; }
        public Nullable<decimal> MS8 { get; set; }
        public Nullable<decimal> MS9 { get; set; }
        public Nullable<decimal> MS10 { get; set; }
        public Nullable<decimal> MS11 { get; set; }
        public Nullable<decimal> MS12 { get; set; }
        public Nullable<int> C6M { get; set; }
        public Nullable<int> C12M { get; set; }
        public Nullable<int> Hits06 { get; set; }
        public Nullable<int> Hits12 { get; set; }
        public Nullable<decimal> DOA { get; set; }
        public Nullable<int> HM1 { get; set; }
        public Nullable<int> HM2 { get; set; }
        public Nullable<int> HM3 { get; set; }
        public Nullable<int> HM4 { get; set; }
        public Nullable<int> HM5 { get; set; }
        public Nullable<int> HM6 { get; set; }
        public Nullable<int> HM7 { get; set; }
        public Nullable<int> HM8 { get; set; }
        public Nullable<int> HM9 { get; set; }
        public Nullable<int> HM10 { get; set; }
        public Nullable<int> HM11 { get; set; }
        public Nullable<int> HM12 { get; set; }
        public Nullable<int> Demanda { get; set; }
        public Nullable<decimal> DemandaProm { get; set; }
        public Nullable<decimal> DemandaS { get; set; }
        public Nullable<decimal> DemandaSProm { get; set; }
        public string ProvCompra { get; set; }
        public Nullable<float> Factor { get; set; }
        public Nullable<sbyte> Stock { get; set; }
        public Nullable<int> Hits03 { get; set; }
        public Nullable<sbyte> ReposicionCongelada { get; set; }
        public Nullable<System.DateTime> ReposicionFechaDeshielo { get; set; }
        public Nullable<int> Demanda6 { get; set; }
        public Nullable<decimal> DemandaProm6 { get; set; }
        public Nullable<decimal> DemandaS6 { get; set; }
        public Nullable<decimal> DemandaSProm6 { get; set; }
        public Nullable<System.DateTime> FechaFinNuevo { get; set; }
        public bool Nuevo { get; set; }
        public Nullable<int> HitsTotal { get; set; }
        public Nullable<decimal> SobreExistencia { get; set; }
        public Nullable<int> NumeroEntrega { get; set; }
        public Nullable<decimal> OTPorRecibir { get; set; }
        public Nullable<decimal> OTPorSurtir { get; set; }
        public Nullable<decimal> Transferir { get; set; }
        public string TransferirAlmacen { get; set; }
        public Nullable<decimal> ImporteCompra { get; set; }
        public Nullable<decimal> ImporteTransferir { get; set; }
    }
}
