//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invplansugeridohistd
    {
        public int ID { get; set; }
        public string Almacen { get; set; }
        public string Articulo { get; set; }
        public string Unidad { get; set; }
        public string TipoDemanda { get; set; }
        public Nullable<decimal> PorRecibir { get; set; }
        public Nullable<decimal> PorSurtir { get; set; }
        public Nullable<decimal> Disponible { get; set; }
        public Nullable<decimal> DisponibleNeto { get; set; }
        public Nullable<decimal> Minimo { get; set; }
        public Nullable<decimal> Maximo { get; set; }
        public Nullable<decimal> Requerimiento { get; set; }
        public Nullable<decimal> Ordenar { get; set; }
        public Nullable<decimal> Sugerido { get; set; }
        public string Proveedor { get; set; }
        public Nullable<int> M1 { get; set; }
        public Nullable<int> M2 { get; set; }
        public Nullable<int> M3 { get; set; }
        public Nullable<int> M4 { get; set; }
        public Nullable<int> M5 { get; set; }
        public Nullable<int> M6 { get; set; }
        public Nullable<int> M7 { get; set; }
        public Nullable<int> M8 { get; set; }
        public Nullable<int> M9 { get; set; }
        public Nullable<int> M10 { get; set; }
        public Nullable<int> M11 { get; set; }
        public Nullable<int> M12 { get; set; }
        public Nullable<int> MS1 { get; set; }
        public Nullable<int> MS2 { get; set; }
        public Nullable<int> MS3 { get; set; }
        public Nullable<int> MS4 { get; set; }
        public Nullable<int> MS5 { get; set; }
        public Nullable<int> MS6 { get; set; }
        public Nullable<int> MS7 { get; set; }
        public Nullable<int> MS8 { get; set; }
        public Nullable<int> MS9 { get; set; }
        public Nullable<int> MS10 { get; set; }
        public Nullable<int> MS11 { get; set; }
        public Nullable<int> MS12 { get; set; }
        public Nullable<decimal> DemandaProm { get; set; }
        public Nullable<decimal> DemandaProm6 { get; set; }
    }
}
