//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invtransfaoe
    {
        public int PID { get; set; }
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public Nullable<bool> SeleccionarE { get; set; }
        public string MovE { get; set; }
        public string FolioE { get; set; }
        public string AlmacenE { get; set; }
        public Nullable<System.DateTime> FechaEmisionE { get; set; }
        public string ArticuloE { get; set; }
        public string DescripcionE { get; set; }
        public Nullable<decimal> CantidadUnidadE { get; set; }
        public string UnidadE { get; set; }
        public Nullable<decimal> CantidadE { get; set; }
        public Nullable<decimal> AvanzarE { get; set; }
        public string AlmacenDE { get; set; }
    }
}
