//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class linkcatalogo
    {
        public string Cuenta { get; set; }
        public string Catalogo { get; set; }
        public int IDInterno { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public string Archivo { get; set; }
        public string Nota { get; set; }
        public string Vinculo { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public byte[] ArchivoDatos { get; set; }
    }
}
