//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class listapreciossdd
    {
        public string Lista { get; set; }
        public string TipoUnidad { get; set; }
        public decimal CargoFijo { get; set; }
        public Nullable<System.DateTime> Antiguedad { get; set; }
        public int KMRecorre { get; set; }
        public int KMRecorreA { get; set; }
    }
}
