//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class listapreciosr2rd
    {
        public string Lista { get; set; }
        public int RenglonID { get; set; }
        public string TipoUnidad { get; set; }
        public decimal CargoFijo { get; set; }
        public Nullable<decimal> CargoxKM { get; set; }
        public Nullable<decimal> CargoxHrRefri { get; set; }
        public Nullable<decimal> CargoxTelemetria { get; set; }
        public Nullable<decimal> KMIncluidos { get; set; }
        public Nullable<decimal> HrRefriIncluidos { get; set; }
        public Nullable<decimal> PorcSemana { get; set; }
        public Nullable<decimal> PorcMes { get; set; }
        public Nullable<decimal> Porc3Meses { get; set; }
        public Nullable<decimal> PorcInterno { get; set; }
        public string ObjetivoMes { get; set; }
        public string MonedaCargoxKm { get; set; }
        public string MonedaCargoxHrRefri { get; set; }
        public string MonedaCargoxTelemetria { get; set; }
        public Nullable<decimal> PrecioCombUnidad { get; set; }
        public Nullable<decimal> PrecioCombThermo { get; set; }
        public Nullable<decimal> PrecioCombUrrea { get; set; }
        public string Modelo { get; set; }
        public string TipoCarroceria { get; set; }
        public Nullable<decimal> CargoRampa { get; set; }
    }
}
