//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m
    {
        public int ID { get; set; }
        public int Empresa { get; set; }
        public string Mov { get; set; }
        public int Sucursal { get; set; }
        public string Folio { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string Usuario { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> FechaConclusion { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public string Referencia { get; set; }
        public string Observaciones { get; set; }
        public string Concepto { get; set; }
        public string Proyecto { get; set; }
        public string Agente { get; set; }
        public string Contacto { get; set; }
        public Nullable<int> ContactoEntrega { get; set; }
        public string Persona { get; set; }
        public string Telefono { get; set; }
        public string Extension { get; set; }
        public string Email { get; set; }
        public string Puesto { get; set; }
        public string Medio { get; set; }
        public string Asunto { get; set; }
        public string Problema { get; set; }
        public string Solucion { get; set; }
        public Nullable<decimal> Avance { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public string WFEstado { get; set; }
        public string WFUsuario { get; set; }
        public string CentroCostos { get; set; }
    }
}
