//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manttoservicio
    {
        public int ID { get; set; }
        public string Contacto { get; set; }
        public string Articulo { get; set; }
        public string Serie { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> RecepUnidad { get; set; }
        public string Ano { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Tipo { get; set; }
        public string Capacidad { get; set; }
        public string NoMotor { get; set; }
        public string Placas { get; set; }
        public string KM { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public string Color { get; set; }
        public string NivelGasolina { get; set; }
        public string NivelAceite { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public string SubCliente { get; set; }
        public string NivelUrea { get; set; }
        public string NivelThermo { get; set; }
        public string Licencia { get; set; }
        public string Operario { get; set; }
        public string Carroceria { get; set; }
        public Nullable<System.DateTime> FechaInicioGarantia { get; set; }
        public Nullable<System.DateTime> FechaFinGarantia { get; set; }
        public Nullable<System.DateTime> FechaRecibo { get; set; }
        public Nullable<System.DateTime> FechaPromesa { get; set; }
        public string TelefonoOperador { get; set; }
        public Nullable<System.DateTime> FechaActualizada { get; set; }
        public string HoraActualizada { get; set; }
        public string HoraPromesa { get; set; }
        public string HoraRecibo { get; set; }
        public string HoraCierre { get; set; }
        public Nullable<bool> ClienteCredito { get; set; }
        public Nullable<int> KMMesUnidad { get; set; }
        public Nullable<System.DateTime> FechaProxServicio { get; set; }
        public Nullable<bool> Interno { get; set; }
        public string NoEconomico { get; set; }
        public Nullable<decimal> HrsExtrasCot { get; set; }
        public Nullable<System.DateTime> FechaAutorizacion { get; set; }
        public string HoraAutorizacion { get; set; }
    }
}
