//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manttoquickcheck
    {
        public int ID { get; set; }
        public int IDInternoI { get; set; }
        public Nullable<bool> Verde { get; set; }
        public Nullable<bool> Amarillo { get; set; }
        public Nullable<bool> Rojo { get; set; }
        public string Comentario { get; set; }
        public Nullable<bool> Evaluar { get; set; }
        public string RefacRequeridas { get; set; }
        public string UsuarioCheck { get; set; }
        public Nullable<System.DateTime> FechaCheck { get; set; }
    }
}
