//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manttoequiposervr2r
    {
        public string Clave { get; set; }
        public string Servicio { get; set; }
        public Nullable<decimal> KM { get; set; }
        public Nullable<int> Dias { get; set; }
    }
}
