//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manttokpi
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public string Usuariokpi { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Hora { get; set; }
        public string Problema { get; set; }
        public string AccionRealizar { get; set; }
        public string KPIWF { get; set; }
        public string TiempoEstandar { get; set; }
        public string TiempoTranscurrido { get; set; }
    }
}
