//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manttocomodatoconfig
    {
        public int Empresa { get; set; }
        public string MovCT { get; set; }
        public string TipoContratoCT { get; set; }
        public string MovCalidadEnc { get; set; }
        public string NormaEnc { get; set; }
        public string RequisitoEnc { get; set; }
        public string ControlEnc { get; set; }
        public string MovCalidadP { get; set; }
        public string NormaP { get; set; }
        public string RequisitoP { get; set; }
        public string ControlP { get; set; }
    }
}
