//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manttosotrefcg
    {
        public int ID { get; set; }
        public int IDInterno { get; set; }
        public string ContactoCG { get; set; }
        public string NombreContactoCG { get; set; }
        public string ArticuloCG { get; set; }
        public string DescripcionCG { get; set; }
        public Nullable<decimal> CantidadUnidadCG { get; set; }
        public string UnidadCG { get; set; }
        public Nullable<decimal> CantidadCG { get; set; }
        public decimal CostoCG { get; set; }
        public decimal TotalCostoCG { get; set; }
        public string MovCG { get; set; }
        public string FolioCG { get; set; }
        public string EstatusCG { get; set; }
        public string WFestadoCG { get; set; }
        public Nullable<bool> TieneGarantiaCG { get; set; }
        public string TipoGarantiaCG { get; set; }
        public string ProveedorRFG { get; set; }
        public Nullable<bool> GarantiaAplicada { get; set; }
        public string ListaPreciosCG { get; set; }
        public Nullable<decimal> PrecioCG { get; set; }
        public decimal TotalPrecioCG { get; set; }
        public Nullable<bool> PaqueteCG { get; set; }
        public string OrigenCG { get; set; }
        public string Descripcion2CG { get; set; }
        public Nullable<bool> ActivarCG { get; set; }
        public string ListaPSAplicaCG { get; set; }
        public string ListaPSAplicaTCG { get; set; }
    }
}
