//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manttod
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public string Tarea { get; set; }
        public bool Correctivo { get; set; }
        public string ArticuloSE { get; set; }
        public string Observaciones { get; set; }
        public string Agente { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public bool Pendiente { get; set; }
        public bool Avanzar { get; set; }
        public Nullable<int> AplicaID { get; set; }
        public Nullable<decimal> PrecioD { get; set; }
        public string ServicioD { get; set; }
        public string TipoMantenimientoD { get; set; }
        public Nullable<decimal> Tiempo { get; set; }
        public bool Adicional { get; set; }
        public string TareaFechaHoraInicio { get; set; }
        public Nullable<int> Cuadrilla { get; set; }
        public string DuracionReal { get; set; }
        public string Duracion { get; set; }
        public Nullable<bool> TieneGarantia { get; set; }
        public string TipoGarantia { get; set; }
        public string ProveedorGD { get; set; }
        public Nullable<bool> GarantiaAplicada { get; set; }
        public string TipoUnidadAliado { get; set; }
        public Nullable<bool> Prioritario { get; set; }
        public Nullable<int> IDInternoItem { get; set; }
        public Nullable<bool> Retrabajo { get; set; }
        public Nullable<bool> Paquete { get; set; }
        public Nullable<bool> Ejecutado { get; set; }
        public string Origen { get; set; }
        public Nullable<bool> Activar { get; set; }
        public string ListaPSAplica { get; set; }
        public string ListaPSAplicaT { get; set; }
        public Nullable<sbyte> Cotizacion { get; set; }
    
        public virtual articulo articulo { get; set; }
        public virtual contacto contacto { get; set; }
    }
}
