//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manttotareagrale
    {
        public int Numero { get; set; }
        public Nullable<int> FrecuenciaGral { get; set; }
        public string UnidadGral { get; set; }
        public string GrupoGral { get; set; }
        public string CategoriaGral { get; set; }
        public string PrioridadGral { get; set; }
        public Nullable<int> HoraGral { get; set; }
        public Nullable<int> MinutoGral { get; set; }
        public bool RequiereParoGral { get; set; }
        public Nullable<int> DiasParoGral { get; set; }
        public bool RequiereMedicion { get; set; }
        public bool ControlValorMaximo { get; set; }
        public Nullable<int> ValorMaximo { get; set; }
        public string UnidadValorMaximo { get; set; }
        public bool ControlValorMinimo { get; set; }
        public Nullable<int> ValorMinimo { get; set; }
        public string UnidadValorMinimo { get; set; }
    }
}
