//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manttosolrefaut
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public string Articulo { get; set; }
        public decimal Cantidad { get; set; }
        public Nullable<decimal> PrecioD { get; set; }
        public string Almacen { get; set; }
        public decimal CantidadUnidad { get; set; }
        public string Unidad { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public string Tarea { get; set; }
        public string Proveedor { get; set; }
        public string TipoSolic { get; set; }
        public string Usuario { get; set; }
        public Nullable<bool> Seleccionar { get; set; }
        public Nullable<bool> TieneGarantia { get; set; }
        public string TipoGarantia { get; set; }
        public string ListaPrecios { get; set; }
        public string Descripcion2 { get; set; }
        public string TipoUnidadEA { get; set; }
        public string MantenimientoTipo { get; set; }
        public string Servicio { get; set; }
        public Nullable<bool> Prioritario { get; set; }
        public string EstatusSolic { get; set; }
        public Nullable<int> IDInternoItem { get; set; }
        public Nullable<bool> Retrabajo { get; set; }
        public Nullable<System.DateTime> FechaAutorizacion { get; set; }
        public Nullable<int> NoCotizacion { get; set; }
        public Nullable<System.DateTime> FechaCotizacion { get; set; }
        public string Origen { get; set; }
        public Nullable<bool> Usado { get; set; }
        public string ListaPSAplica { get; set; }
        public string ListaPSAplicaT { get; set; }
        public Nullable<int> RenglonIDMantto { get; set; }
    }
}
