//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manttomovporctot
    {
        public string Mov { get; set; }
        public decimal Porc { get; set; }
        public decimal PrecioXHr { get; set; }
        public string MantenimientoTipo { get; set; }
        public string Servicio { get; set; }
        public string ArticuloConsumibles { get; set; }
        public Nullable<decimal> PrecioxConsumibles { get; set; }
        public Nullable<decimal> LimiteSinAnticipo { get; set; }
        public string LimiteSinAnticipoMoneda { get; set; }
        public Nullable<decimal> PorAnticipo { get; set; }
        public Nullable<int> KMUnidadServ { get; set; }
        public string Almacen { get; set; }
    }
}
