//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manttoserviciosunidad
    {
        public int ID { get; set; }
        public int Empresa { get; set; }
        public int Sucursal { get; set; }
        public string OT { get; set; }
        public string FechaVenta { get; set; }
        public string FechaSalida { get; set; }
        public string AgenteE { get; set; }
        public string NombreAgente { get; set; }
        public string VIN { get; set; }
        public string NombreCliente { get; set; }
        public string Movimiento { get; set; }
    }
}
