//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manttosotrefinv
    {
        public int ID { get; set; }
        public int RenglonIDMA { get; set; }
        public int IDInterno { get; set; }
        public string ContactoI { get; set; }
        public string NombreContactoI { get; set; }
        public string ArticuloI { get; set; }
        public string DescripcionI { get; set; }
        public Nullable<decimal> CantidadUnidadI { get; set; }
        public Nullable<decimal> CantidadEntregada { get; set; }
        public Nullable<decimal> CantidadRecibida { get; set; }
        public Nullable<decimal> CantidadDevuelta { get; set; }
        public string UnidadI { get; set; }
        public Nullable<decimal> CantidadI { get; set; }
        public decimal CostoI { get; set; }
        public decimal TotalCostoI { get; set; }
        public string MovI { get; set; }
        public string FolioI { get; set; }
        public string EstatusI { get; set; }
        public string WFestadoI { get; set; }
        public Nullable<bool> TieneGarantiaI { get; set; }
        public string TipoGarantiaI { get; set; }
        public string ProveedorRFG { get; set; }
        public Nullable<bool> GarantiaAplicada { get; set; }
        public string ListaPreciosI { get; set; }
        public Nullable<decimal> PrecioI { get; set; }
        public decimal TotalPrecioI { get; set; }
        public int IDInv { get; set; }
        public Nullable<bool> PaqueteI { get; set; }
        public string OrigenI { get; set; }
        public Nullable<bool> ActivarINV { get; set; }
        public string ListaPSAplicaINV { get; set; }
        public string ListaPSAplicaTINV { get; set; }
        public string Cores { get; set; }
        public Nullable<decimal> CoresDevueltos { get; set; }
    }
}
