//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manttoequipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public manttoequipo()
        {
            this.manttomovequipoes = new HashSet<manttomovequipo>();
        }
    
        public string Clave { get; set; }
        public string Descripcion { get; set; }
        public string Tecnologia { get; set; }
        public string Marca { get; set; }
        public string EquipoTipo { get; set; }
        public string Modelo { get; set; }
        public string Placas { get; set; }
        public string Legal { get; set; }
        public string Motor { get; set; }
        public string Chasis { get; set; }
        public string TarjetaCirculacion { get; set; }
        public string TarjetaCasetas { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<System.DateTime> UltimoMantenimiento { get; set; }
        public Nullable<int> UltimoMantenimientoDesgaste { get; set; }
        public string Observaciones { get; set; }
        public bool Utilizado { get; set; }
        public Nullable<int> Empresa { get; set; }
        public string MantenimientoTipo { get; set; }
        public Nullable<int> DesgasteAnterior { get; set; }
        public Nullable<int> DesgasteActual { get; set; }
        public Nullable<System.DateTime> Antiguedad { get; set; }
        public bool Interno { get; set; }
        public string Articulo { get; set; }
        public string Serie { get; set; }
        public bool Medidor { get; set; }
        public Nullable<int> DesgasteTeorico { get; set; }
        public bool ServicioExterno { get; set; }
        public Nullable<int> DesgasteTeoricoAnterior { get; set; }
        public Nullable<decimal> Rendimiento { get; set; }
        public string CentroCostos { get; set; }
        public string OperadorOmision { get; set; }
        public string RemolqueOmision { get; set; }
        public string Capacidad { get; set; }
        public string Grupo { get; set; }
        public string Categoria { get; set; }
        public string Ubicacion { get; set; }
        public string PrioridadMantto { get; set; }
        public bool ChcEquipoPadre { get; set; }
        public string EquipoPadre { get; set; }
        public Nullable<int> Frecuencia { get; set; }
        public string UnidadFrecuencia { get; set; }
        public Nullable<int> DesgastePromedio { get; set; }
        public Nullable<int> DesgasteMaximo { get; set; }
        public bool ValidarGarantia { get; set; }
        public Nullable<System.DateTime> FechaGarantia { get; set; }
        public string Color { get; set; }
        public string TipoVeh { get; set; }
        public string Ano { get; set; }
        public string Operador { get; set; }
        public string Licencia { get; set; }
        public string TipoCarroceria { get; set; }
        public Nullable<System.DateTime> FechaInicioGarantia { get; set; }
        public Nullable<System.DateTime> FechaFinGarantia { get; set; }
        public string NoEconomico { get; set; }
        public string GrupoContrato { get; set; }
        public string EstatusContrato { get; set; }
        public string EstatusVenta { get; set; }
        public Nullable<decimal> CapTanqueDiesel { get; set; }
        public string EquipoAliado { get; set; }
        public Nullable<decimal> Thermo { get; set; }
        public Nullable<decimal> Largo { get; set; }
        public Nullable<decimal> Ancho { get; set; }
        public Nullable<decimal> Alto { get; set; }
        public Nullable<decimal> Volumen { get; set; }
        public string TipoSeguro { get; set; }
        public Nullable<System.DateTime> FechaTerminoSeguro { get; set; }
        public string NoPoliza { get; set; }
        public string EndosoPoliza { get; set; }
        public Nullable<decimal> kmmesprom { get; set; }
        public Nullable<decimal> Costokmtotal { get; set; }
        public Nullable<decimal> costokmllanta { get; set; }
        public string MarcaEquipoAliado { get; set; }
        public Nullable<decimal> CapacidadUrea { get; set; }
        public string ModeloRampa { get; set; }
        public string ModeloThermo { get; set; }
        public Nullable<bool> Comodato { get; set; }
        public Nullable<decimal> PrecioUnidad { get; set; }
        public Nullable<decimal> PrecioComodato { get; set; }
        public string UbicacionActual { get; set; }
        public Nullable<int> KMRecorreMes { get; set; }
        public string NoMotor { get; set; }
        public Nullable<bool> UnidadForanea { get; set; }
        public string Cliente { get; set; }
        public Nullable<int> Sucursal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<manttomovequipo> manttomovequipoes { get; set; }
        public virtual manttomarca manttomarca { get; set; }
    }
}
