//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class manttomodelo
    {
        public string Modelo { get; set; }
        public string TipoUnidad { get; set; }
        public string Marca { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> SPECCMIBase { get; set; }
        public Nullable<decimal> SPECCMIStocking { get; set; }
        public Nullable<decimal> SPECCACESABase { get; set; }
        public Nullable<decimal> SPECCACESAStocking { get; set; }
        public string Clave { get; set; }
        public string SPA { get; set; }
        public string PROPTOPS { get; set; }
        public string Motor { get; set; }
        public string Torque { get; set; }
        public string Embrague { get; set; }
        public string Transmision { get; set; }
        public string EjeDelantero { get; set; }
        public string EjeTrasero { get; set; }
        public string SuspDelantera { get; set; }
        public string SuspTrasera { get; set; }
        public string Llantas { get; set; }
        public string Tanques { get; set; }
        public string Direccion { get; set; }
        public string Frenos { get; set; }
        public string Bastidor { get; set; }
        public string Camarote { get; set; }
        public string PBVPBC { get; set; }
        public string Ejes { get; set; }
        public string Configuracion { get; set; }
        public string ClaveVehicular { get; set; }
        public string PesoVehicular { get; set; }
        public string Clase { get; set; }
        public string Altura { get; set; }
        public string Ancho { get; set; }
        public string Largo { get; set; }
        public string Capacidad { get; set; }
        public string Estatus { get; set; }
        public string Cabina { get; set; }
        public string ModeloAno { get; set; }
        public string ImagenRuta { get; set; }
        public byte[] Imagen { get; set; }
        public string Accesorios { get; set; }
        public string Garantia { get; set; }
    }
}
