//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensaje
    {
        public string Mensaje1 { get; set; }
        public string Tipo { get; set; }
        public string Grupo { get; set; }
        public string Espanol { get; set; }
        public string Ingles { get; set; }
        public string Frances { get; set; }
        public string Portugues { get; set; }
        public string Italiano { get; set; }
        public string Aleman { get; set; }
        public string Ruso { get; set; }
        public string Indi { get; set; }
        public string Chino { get; set; }
        public string Coreano { get; set; }
        public string Japones { get; set; }
        public string Arabe { get; set; }
    }
}
