//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menusistema
    {
        public int Empresa { get; set; }
        public Nullable<int> Nivel { get; set; }
        public string Nombre { get; set; }
        public string Icono { get; set; }
        public string Accion { get; set; }
        public string Espanol { get; set; }
        public string Ingles { get; set; }
        public string Frances { get; set; }
        public string Portugues { get; set; }
        public string Italiano { get; set; }
        public string Aleman { get; set; }
        public string Ruso { get; set; }
        public string Indi { get; set; }
        public string Chino { get; set; }
        public string Coreano { get; set; }
        public string Japones { get; set; }
        public string Arabe { get; set; }
        public string lang1 { get; set; }
        public string lang2 { get; set; }
        public string lang3 { get; set; }
        public string lang4 { get; set; }
        public string lang5 { get; set; }
        public string lang6 { get; set; }
        public string lang7 { get; set; }
        public string lang8 { get; set; }
        public string lang9 { get; set; }
        public long orden { get; set; }
        public Nullable<bool> visible { get; set; }
    }
}
