//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class modeloarticulo
    {
        public string Modelo { get; set; }
        public string Renglon { get; set; }
        public string Columna { get; set; }
        public string Articulo { get; set; }
    
        public virtual modelo modelo1 { get; set; }
    }
}
