//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class moneda
    {
        public string Moneda1 { get; set; }
        public decimal TipoCambio { get; set; }
        public Nullable<decimal> TipoCambioCompra { get; set; }
        public Nullable<decimal> TipoCambioVenta { get; set; }
        public string CodigoSat { get; set; }
        public Nullable<int> Decimales { get; set; }
        public Nullable<decimal> PorcVariacion { get; set; }
    }
}
