//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movdavance
    {
        public int IDInterno { get; set; }
        public int PID { get; set; }
        public string Modulo { get; set; }
        public int ID { get; set; }
        public string Mov { get; set; }
        public string Folio { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string Articulo { get; set; }
        public Nullable<decimal> CantidadPendiente { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> DescuentoLinea { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public bool Seleccionar { get; set; }
        public Nullable<decimal> CantidadUnidad { get; set; }
        public string Unidad { get; set; }
        public Nullable<decimal> DeduciblePorcentaje { get; set; }
        public string ReferenciaCG { get; set; }
        public string ReferenciaInv { get; set; }
        public string ReferenciaVTA { get; set; }
        public string CentroCostosD { get; set; }
        public Nullable<decimal> IGI { get; set; }
        public Nullable<decimal> DescuentoImporte { get; set; }
        public string NoConfirmacion { get; set; }
        public string VIN { get; set; }
        public Nullable<decimal> PrecioRX { get; set; }
        public string Descripcion2 { get; set; }
        public Nullable<int> IDSolicOrigen { get; set; }
    }
}
