//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movrastreo
    {
        public string OModulo { get; set; }
        public int OID { get; set; }
        public string OMov { get; set; }
        public string OFolio { get; set; }
        public string DModulo { get; set; }
        public int DID { get; set; }
        public string DMov { get; set; }
        public string DFolio { get; set; }
        public Nullable<bool> Cancelado { get; set; }
    }
}
