//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movvencido
    {
        public int PID { get; set; }
        public string Modulo { get; set; }
        public int ID { get; set; }
        public Nullable<int> Empresa { get; set; }
        public string Mov { get; set; }
        public Nullable<int> Sucursal { get; set; }
        public string Folio { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaVenceMov { get; set; }
        public string Estatus { get; set; }
        public string Referencia { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> DiasVencido { get; set; }
        public string Concepto { get; set; }
        public string Proyecto { get; set; }
        public string Contacto { get; set; }
        public string Almacen { get; set; }
        public string AlmacenDestino { get; set; }
        public Nullable<int> RenglonID { get; set; }
        public string Articulo { get; set; }
        public Nullable<decimal> CantidadUnidad { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string Unidad { get; set; }
        public Nullable<decimal> CantidadPendiente { get; set; }
        public Nullable<decimal> CantidadA { get; set; }
        public Nullable<bool> Seleccionar { get; set; }
    }
}
