//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nominaprevio
    {
        public int ID { get; set; }
        public string Contacto { get; set; }
        public string ClaveCalc { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public string Dato { get; set; }
        public Nullable<bool> ISR { get; set; }
        public string ISRCondicion { get; set; }
        public Nullable<decimal> ISRImporte { get; set; }
        public Nullable<bool> Cxp { get; set; }
        public string CxpContacto { get; set; }
        public string DatoCantidad { get; set; }
        public Nullable<bool> Cxc { get; set; }
        public string Concepto { get; set; }
    }
}
