//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nominacontratotipo
    {
        public string Contrato { get; set; }
        public Nullable<int> Meses { get; set; }
        public Nullable<int> Dispmag { get; set; }
        public string ClaveSat { get; set; }
    }
}
