//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nominavariablelista
    {
        public string Variable { get; set; }
        public string Grupo { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public Nullable<bool> EnEmpresa { get; set; }
        public Nullable<bool> EnSucursal { get; set; }
        public Nullable<bool> EnCategoria { get; set; }
        public Nullable<bool> EnPuesto { get; set; }
        public Nullable<bool> EnContacto { get; set; }
        public string ValorOmision { get; set; }
    }
}
