//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nominaturno
    {
        public int ID { get; set; }
        public string Usuario { get; set; }
        public string Personal { get; set; }
        public string Jornada { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public System.DateTime FechaInicial { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public string Estatus { get; set; }
        public Nullable<int> IDAP { get; set; }
    }
}
