//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nominacalcd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nominacalcd()
        {
            this.contactonominacuentas = new HashSet<contactonominacuenta>();
        }
    
        public int ID { get; set; }
        public string Clave { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public string Formula { get; set; }
        public Nullable<bool> ISR { get; set; }
        public string ISRCondicion { get; set; }
        public string ISRFormula { get; set; }
        public Nullable<bool> Cxp { get; set; }
        public string Contacto { get; set; }
        public bool ISRGravableAcumular { get; set; }
        public bool IMSSGravableAcumular { get; set; }
        public string IEGravableAcumular { get; set; }
        public string FormulaCantidad { get; set; }
        public bool Contabilizar { get; set; }
        public string ContCuenta { get; set; }
        public string CargoAbono { get; set; }
        public Nullable<bool> Cxc { get; set; }
        public string Concepto { get; set; }
        public string ContTipo { get; set; }
        public Nullable<bool> Cuadre { get; set; }
        public Nullable<bool> CxCFDI { get; set; }
        public string Comentarios { get; set; }
        public bool ProrrateaCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contactonominacuenta> contactonominacuentas { get; set; }
        public virtual nominacfdiconcepto nominacfdiconcepto { get; set; }
    }
}
