//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nominacfdiconcepto
    {
        public int ID { get; set; }
        public string Clave { get; set; }
        public string Tipo { get; set; }
        public string SATPercepcion { get; set; }
        public string SATDeduccion { get; set; }
        public string TipoGE { get; set; }
        public string SubTipo { get; set; }
        public string TipoIncapacidad { get; set; }
        public string TipoHoraExtra { get; set; }
        public string ClaveSat { get; set; }
        public string CIngresoNoAcumulable { get; set; }
        public string CIngresoAcumulable { get; set; }
    
        public virtual nominacalcd nominacalcd { get; set; }
    }
}
