//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nominad
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public string ContactoD { get; set; }
        public string Clave { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string Tipo { get; set; }
        public string AplicaModulo { get; set; }
        public Nullable<int> AplicaID { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
    
        public virtual contacto contacto { get; set; }
    }
}
