//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nominacfdicontacto
    {
        public int ID { get; set; }
        public string Contacto { get; set; }
        public string Version { get; set; }
        public string RegistroPatronal { get; set; }
        public string CURP { get; set; }
        public string TipoRegimen { get; set; }
        public string NumSeguridadSocial { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<System.DateTime> FechaInicialPago { get; set; }
        public Nullable<System.DateTime> FechaFinalPago { get; set; }
        public Nullable<int> NumDiasPagados { get; set; }
        public string Departamento { get; set; }
        public string CLABE { get; set; }
        public string Banco { get; set; }
        public Nullable<System.DateTime> FechaInicioRelLaboral { get; set; }
        public string Antiguedad { get; set; }
        public string Puesto { get; set; }
        public string TipoContrato { get; set; }
        public string TipoJornada { get; set; }
        public string PeriodicidadPago { get; set; }
        public Nullable<decimal> SalarioBaseCotApor { get; set; }
        public string RiesgoPuesto { get; set; }
        public Nullable<decimal> SalarioDiarioIntegrado { get; set; }
        public Nullable<decimal> TotalPercepciones { get; set; }
        public Nullable<decimal> PercepcionesGravadas { get; set; }
        public Nullable<decimal> PercepcionesExentas { get; set; }
        public Nullable<decimal> TotalDeducciones { get; set; }
        public Nullable<decimal> DeduccionesGravadas { get; set; }
        public Nullable<decimal> DeduccionesExentas { get; set; }
        public Nullable<decimal> TotalIncapacidad { get; set; }
        public Nullable<decimal> TotalHorasExtra { get; set; }
        public bool Timbrado { get; set; }
        public string UUID { get; set; }
        public string Mensaje { get; set; }
        public string CadenaOriginal { get; set; }
        public string SelloDigital { get; set; }
        public string XML { get; set; }
        public string FechaCFDI { get; set; }
        public string PacCadenaOriginal { get; set; }
        public string PacSelloSAT { get; set; }
        public string PacVersion { get; set; }
        public string PacNoCertificado { get; set; }
        public string PacFechaTimbrado { get; set; }
        public byte[] codigobidimensional { get; set; }
        public string RutaArchivoXML { get; set; }
        public string Sindicalizado { get; set; }
        public Nullable<decimal> TotalOtrosPagos { get; set; }
        public Nullable<decimal> OtrosPagosGravadas { get; set; }
        public Nullable<decimal> OtrosPagosExentas { get; set; }
        public Nullable<decimal> SubsidioCausado { get; set; }
        public string UUIDCancelado { get; set; }
        public Nullable<decimal> TotalOtrasDeducciones { get; set; }
        public Nullable<decimal> TotalImpuestosRetenidos { get; set; }
        public Nullable<decimal> SubsidioCausadoAcumulado { get; set; }
    }
}
