//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nominacontacto
    {
        public int ID { get; set; }
        public string Contacto { get; set; }
        public Nullable<int> Sucursal { get; set; }
        public string Departamento { get; set; }
        public string Puesto { get; set; }
        public string Categoria { get; set; }
        public string ZonaEconomica { get; set; }
        public string Jornada { get; set; }
        public Nullable<decimal> SueldoDiario { get; set; }
        public Nullable<decimal> SDI { get; set; }
        public string RegistroPatronal { get; set; }
        public string PrimaRiesgo { get; set; }
        public string CentroCostos { get; set; }
        public string ClaveRiesgo { get; set; }
    
        public virtual contacto contacto1 { get; set; }
    }
}
