//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class objetivocomprav
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public string VMes { get; set; }
        public Nullable<decimal> VObjetivoCompra { get; set; }
        public string VMoneda { get; set; }
        public Nullable<decimal> VTipoCambio { get; set; }
        public Nullable<decimal> VObjetivoCompraMXN { get; set; }
        public Nullable<decimal> VCompraReal { get; set; }
        public Nullable<decimal> VPorcAlcanzado { get; set; }
        public string VIncentivoTipo { get; set; }
        public bool VIncentivoGanado { get; set; }
        public string VIncentivoEstatus { get; set; }
    }
}
