//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedimentorectificacion
    {
        public string NumeroR { get; set; }
        public string ClaveR { get; set; }
        public string RegimenR { get; set; }
        public string TipoIER { get; set; }
        public string TipoR { get; set; }
        public Nullable<System.DateTime> VencimientoR { get; set; }
        public Nullable<decimal> ValorDolaresR { get; set; }
        public Nullable<decimal> ValorAduanaR { get; set; }
        public Nullable<decimal> ValorComercialR { get; set; }
        public Nullable<int> AduanaR { get; set; }
        public string AgenteAduanalR { get; set; }
        public string EmbarqueOrdenR { get; set; }
        public Nullable<System.DateTime> FechaEntradaR { get; set; }
        public string ObservacionesR { get; set; }
    }
}
