//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedimento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedimento()
        {
            this.pedimentods = new HashSet<pedimentod>();
            this.pedimentoremesas = new HashSet<pedimentoremesa>();
        }
    
        public string Numero { get; set; }
        public string Clave { get; set; }
        public string Regimen { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> Vencimiento { get; set; }
        public Nullable<decimal> ValorDolares { get; set; }
        public Nullable<decimal> ValorAduana { get; set; }
        public Nullable<decimal> ValorComercial { get; set; }
        public Nullable<int> Aduana { get; set; }
        public string AgenteAduanal { get; set; }
        public string EmbarqueOrden { get; set; }
        public System.DateTime FechaEntrada { get; set; }
        public bool Utilizado { get; set; }
        public string TipoIE { get; set; }
        public string Documento { get; set; }
        public Nullable<System.DateTime> DocumentoFecha { get; set; }
        public string Guia { get; set; }
        public Nullable<System.DateTime> GuiaFecha { get; set; }
        public string Convenio { get; set; }
        public Nullable<int> Paquetes { get; set; }
        public string PuertoCarga { get; set; }
        public Nullable<System.DateTime> FechaCarga { get; set; }
        public string PuertoDestino { get; set; }
        public Nullable<System.DateTime> FechaDestino { get; set; }
        public Nullable<int> CertificadoOrigen { get; set; }
        public string NumCertificadoOrigen { get; set; }
        public string NumeroExportadorConfiable { get; set; }
        public string Incoterm { get; set; }
        public Nullable<int> Subdivision { get; set; }
        public string Observaciones { get; set; }
        public Nullable<decimal> TipoCambioUSD { get; set; }
        public Nullable<decimal> TotalUSD { get; set; }
        public string TipoOperacion { get; set; }
        public bool Rectificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedimentod> pedimentods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedimentoremesa> pedimentoremesas { get; set; }
    }
}
