//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodrutad
    {
        public string Ruta { get; set; }
        public int Orden { get; set; }
        public string Centro { get; set; }
        public string Operacion { get; set; }
        public Nullable<decimal> TiempoFijo { get; set; }
        public Nullable<decimal> TiempoVariable { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public string Moneda { get; set; }
    
        public virtual prodcentro prodcentro { get; set; }
        public virtual prodruta prodruta { get; set; }
    }
}
