//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodcentro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prodcentro()
        {
            this.prodarticulooperacions = new HashSet<prodarticulooperacion>();
            this.prodrutads = new HashSet<prodrutad>();
        }
    
        public string Centro { get; set; }
        public string Descripcion { get; set; }
        public string Estatus { get; set; }
        public string Tipo { get; set; }
        public string Almacen { get; set; }
        public string CentroCostos { get; set; }
        public Nullable<decimal> CostoDirecto { get; set; }
        public Nullable<decimal> CostoInDirecto { get; set; }
        public string CostoMoneda { get; set; }
        public Nullable<int> Capacidad { get; set; }
        public Nullable<decimal> PorcUtilizacion { get; set; }
        public Nullable<decimal> Eficiencia { get; set; }
        public Nullable<decimal> TiempoProceso { get; set; }
        public Nullable<decimal> TiempoEspera { get; set; }
        public bool Utilizado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prodarticulooperacion> prodarticulooperacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prodrutad> prodrutads { get; set; }
    }
}
