//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pvreporte
    {
        public string Reporte { get; set; }
        public string Nombre { get; set; }
        public string TipoSaldo { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<bool> Pantalla { get; set; }
        public Nullable<bool> Impresora { get; set; }
        public Nullable<bool> PDF { get; set; }
    }
}
