//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class renivelinvd
    {
        public int IDD { get; set; }
        public int RenglonID { get; set; }
        public string Articulo { get; set; }
        public Nullable<int> MesesSinHitsOrigD { get; set; }
        public string RankingHCOrigD { get; set; }
        public Nullable<decimal> CantidadUnidad { get; set; }
        public string Unidad { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string AlmacenD { get; set; }
        public string AlmacenDestinoD { get; set; }
        public string RankingHCDestD { get; set; }
        public Nullable<int> MesesSinHitsDestD { get; set; }
        public bool Seleccionar { get; set; }
    }
}
