//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rutad
    {
        public string Ruta { get; set; }
        public int Numero { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public int Distancia { get; set; }
    
        public virtual ruta ruta1 { get; set; }
    }
}
