//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class serielote
    {
        public int Empresa { get; set; }
        public string Almacen { get; set; }
        public string Articulo { get; set; }
        public string SerieLote1 { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> Caducidad { get; set; }
        public string Pedimento { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public string NoMotor { get; set; }
        public string AnoVIN { get; set; }
        public string MarcaVIN { get; set; }
        public string ModeloVIN { get; set; }
        public string TipoVIN { get; set; }
        public string NoInventario { get; set; }
        public Nullable<bool> EsNueva { get; set; }
        public string ColorVIN { get; set; }
        public Nullable<int> km { get; set; }
        public string Descripcion2SL { get; set; }
    }
}
