//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sucursal
    {
        public int Sucursal1 { get; set; }
        public string Nombre { get; set; }
        public string PreFijo { get; set; }
        public string Estatus { get; set; }
        public string Direccion { get; set; }
        public string Colonia { get; set; }
        public string Poblacion { get; set; }
        public string Estado { get; set; }
        public string Codigopostal { get; set; }
        public string Pais { get; set; }
        public string Telefonos { get; set; }
        public string Fax { get; set; }
        public string Grupo { get; set; }
        public string AlmacenOmision { get; set; }
        public string ListaPreciosOmision { get; set; }
        public string CentroCostos { get; set; }
        public bool Utilizado { get; set; }
        public string ZonaImpuesto { get; set; }
        public string FERutaXML { get; set; }
        public string FERutaCertificado { get; set; }
        public string FERutaKey { get; set; }
        public string FEClaveLlave { get; set; }
        public string FERutaXMLCancelado { get; set; }
        public string FERutaPFX { get; set; }
        public string CertificadoTXT { get; set; }
        public string CertificadoSerie { get; set; }
        public string CertificadoFechaD { get; set; }
        public string CertificadoFechaA { get; set; }
        public string FERutaXMLNomina { get; set; }
        public string AlmacenCompra { get; set; }
        public string AlmacenInv { get; set; }
        public string LlaveCertificadoTXT { get; set; }
        public string AlmacenGarantia { get; set; }
        public string ListaSegmentoOmision { get; set; }
        public string ZonaHoraria { get; set; }
    }
}
