//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicacioncalendario
    {
        public int ID { get; set; }
        public Nullable<int> Empresa { get; set; }
        public Nullable<int> Sucursal { get; set; }
        public string Modulo { get; set; }
        public Nullable<int> ModuloID { get; set; }
        public Nullable<int> RenglonID { get; set; }
        public string Articulo { get; set; }
        public Nullable<int> Ubicacion { get; set; }
        public Nullable<System.DateTime> FechaD { get; set; }
        public Nullable<System.DateTime> FechaA { get; set; }
    
        public virtual ubicacion ubicacion1 { get; set; }
    }
}
