//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ubicacion()
        {
            this.ubicacioncalendarios = new HashSet<ubicacioncalendario>();
            this.ubicacionmovs = new HashSet<ubicacionmov>();
        }
    
        public int Ubicacion1 { get; set; }
        public string Nombre { get; set; }
        public string Estatus { get; set; }
        public int Sucursal { get; set; }
        public string Almacen { get; set; }
        public Nullable<int> Cupo { get; set; }
        public bool Utilizado { get; set; }
        public bool SeRenta { get; set; }
        public string Articulo { get; set; }
        public string Grupo { get; set; }
        public string UnidadTiempo { get; set; }
        public string HoraD { get; set; }
        public string HoraA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ubicacioncalendario> ubicacioncalendarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ubicacionmov> ubicacionmovs { get; set; }
    }
}
