//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.usuarioconfigs = new HashSet<usuarioconfig>();
            this.wfusuarios = new HashSet<wfusuario>();
        }
    
        public string Usuario1 { get; set; }
        public string Nombre { get; set; }
        public string GrupoTrabajo { get; set; }
        public string Departamento { get; set; }
        public string Contrasena { get; set; }
        public string ContrasenaConfirmacion { get; set; }
        public Nullable<System.DateTime> ContrasenaFecha { get; set; }
        public string Telefono { get; set; }
        public string Extension { get; set; }
        public string Estatus { get; set; }
        public string AgenteOmision { get; set; }
        public bool Utilizado { get; set; }
        public string CuentaBancoOmision { get; set; }
        public Nullable<int> EmpresaUltimoAcceso { get; set; }
        public Nullable<int> SucursalUltimoAcceso { get; set; }
        public Nullable<int> IdiomaUltimoAcceso { get; set; }
        public string Email { get; set; }
        public string EmailPassword { get; set; }
        public string EmailUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarioconfig> usuarioconfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wfusuario> wfusuarios { get; set; }
    }
}
