//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilrcmova
    {
        public string Usuario { get; set; }
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public Nullable<int> AplicaID { get; set; }
        public string MovA { get; set; }
        public string FolioA { get; set; }
        public Nullable<System.DateTime> FechaA { get; set; }
        public string NoConfirmacionA { get; set; }
        public string ContactoDA { get; set; }
        public string NombreProveedorA { get; set; }
        public string ReferenciaA { get; set; }
        public string NoParteA { get; set; }
        public string ArticuloA { get; set; }
        public string DecripcionA { get; set; }
        public Nullable<decimal> CantidadUnidadA { get; set; }
        public string UnidadA { get; set; }
        public Nullable<decimal> CantidadAA { get; set; }
        public Nullable<decimal> CantidadPendienteA { get; set; }
        public float FactorA { get; set; }
        public Nullable<decimal> CantidadAAA { get; set; }
        public Nullable<bool> SeleccionarA { get; set; }
    }
}
