//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilmanttor
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public string ArticuloI { get; set; }
        public Nullable<decimal> CantidadI { get; set; }
        public decimal PrecioI { get; set; }
        public Nullable<decimal> CantidadUnidadI { get; set; }
        public string UnidadI { get; set; }
        public string TipoGarantiaI { get; set; }
        public string ProveedorI { get; set; }
        public string AlmacenI { get; set; }
        public string ListaPreciosI { get; set; }
    }
}
