//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilfacturacionctd
    {
        public string PID { get; set; }
        public Nullable<bool> Seleccionar { get; set; }
        public Nullable<int> ID { get; set; }
        public string TipoContrato { get; set; }
        public string Cliente { get; set; }
        public string NombreCliente { get; set; }
        public Nullable<int> IDUnidad { get; set; }
        public string ModeloFact { get; set; }
        public string Eco { get; set; }
        public string Serie { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Plazo { get; set; }
        public Nullable<decimal> CargoFijo { get; set; }
        public Nullable<int> KMINI { get; set; }
        public Nullable<int> KMFIN { get; set; }
        public Nullable<decimal> KMaRecorrer { get; set; }
        public Nullable<decimal> KMIncluidos { get; set; }
        public Nullable<decimal> KMCobrar { get; set; }
        public Nullable<decimal> CargoxKM { get; set; }
        public Nullable<decimal> MontoKM { get; set; }
        public Nullable<decimal> HrRefriIni { get; set; }
        public Nullable<decimal> HrRefriFin { get; set; }
        public Nullable<decimal> HrRefri { get; set; }
        public Nullable<decimal> HrRefriIncluidos { get; set; }
        public Nullable<decimal> HrRefriAcobrar { get; set; }
        public Nullable<decimal> MontoRefri { get; set; }
        public Nullable<decimal> CargoxDiesel { get; set; }
        public Nullable<decimal> CargoxUrea { get; set; }
        public Nullable<decimal> CargoxThermo { get; set; }
        public Nullable<decimal> CombUnidadIni { get; set; }
        public Nullable<decimal> CombUnidadFin { get; set; }
        public Nullable<decimal> CombUnidadInc { get; set; }
        public Nullable<decimal> CombUreaIni { get; set; }
        public Nullable<decimal> CombUreaFin { get; set; }
        public Nullable<decimal> CombUreaInc { get; set; }
        public Nullable<decimal> CombRefriIni { get; set; }
        public Nullable<decimal> CombRefriFin { get; set; }
        public Nullable<decimal> CombRefriInc { get; set; }
        public Nullable<decimal> ImporteFacturar { get; set; }
        public string PeriodoFactura { get; set; }
        public string PeriodoTotal { get; set; }
        public string DiaFactura { get; set; }
        public string Seguro { get; set; }
        public Nullable<System.DateTime> FechaExpira { get; set; }
        public string ContratoAplica { get; set; }
        public string ContratoConceptoAplica { get; set; }
        public Nullable<decimal> CargoxHrRefri { get; set; }
        public Nullable<decimal> CargoxTelemetria { get; set; }
        public Nullable<decimal> CargoAbusos { get; set; }
        public Nullable<decimal> CargoCombustible { get; set; }
        public Nullable<decimal> CargoCombustibleTracto { get; set; }
        public Nullable<decimal> CargoCombustibleTermo { get; set; }
        public Nullable<decimal> CargoCombustibleUrea { get; set; }
    }
}
