//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilrc
    {
        public string Usuario { get; set; }
        public string CodigoBarras { get; set; }
        public string NoParteC { get; set; }
        public string ArticuloC { get; set; }
        public string DescripcionC { get; set; }
        public Nullable<decimal> CantidadUnidadC { get; set; }
        public string UnidadC { get; set; }
        public Nullable<decimal> CantidadC { get; set; }
    }
}
