//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilmanttokpi
    {
        public int PID { get; set; }
        public int ID { get; set; }
        public string KPIWF { get; set; }
        public string TiempoEstandar { get; set; }
        public string TiempoTranscurrido { get; set; }
        public string Movimiento { get; set; }
        public string Folio { get; set; }
        public string Cliente { get; set; }
        public string Nombre { get; set; }
        public string TipoUnidad { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public string Vin { get; set; }
        public string Problema { get; set; }
        public string AccionRealizar { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Hora { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaActualizada { get; set; }
        public string TiempoTranscurridoEstado { get; set; }
        public string TiempoTranscurridoTotal { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> FechaEstado { get; set; }
        public string HoraActualizada { get; set; }
        public string Concepto { get; set; }
        public string NoEconomico { get; set; }
    }
}
