//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilfacturacionctdaux
    {
        public int IDInterno { get; set; }
        public Nullable<int> IDMovGen { get; set; }
        public string MovAplica { get; set; }
        public Nullable<int> ID { get; set; }
        public string TipoContrato2 { get; set; }
        public string Cliente2 { get; set; }
        public string NombreCliente2 { get; set; }
        public Nullable<int> IDUnidad2 { get; set; }
        public string ModeloFact2 { get; set; }
        public string Eco2 { get; set; }
        public string Serie2 { get; set; }
        public Nullable<decimal> CargoFijo2 { get; set; }
        public Nullable<int> KMINI2 { get; set; }
        public Nullable<int> KMFIN2 { get; set; }
        public Nullable<decimal> KMaRecorrer2 { get; set; }
        public Nullable<decimal> KMIncluidos2 { get; set; }
        public Nullable<decimal> KMCobrar2 { get; set; }
        public Nullable<decimal> CargoxKM2 { get; set; }
        public Nullable<decimal> MontoKM2 { get; set; }
        public Nullable<decimal> HrRefriIni2 { get; set; }
        public Nullable<decimal> HrRefriFin2 { get; set; }
        public Nullable<decimal> HrRefri2 { get; set; }
        public Nullable<decimal> HrRefriIncluidos2 { get; set; }
        public Nullable<decimal> HrRefriAcobrar2 { get; set; }
        public Nullable<decimal> MontoRefri2 { get; set; }
        public Nullable<decimal> CargoxDiesel { get; set; }
        public Nullable<decimal> CargoxUrea { get; set; }
        public Nullable<decimal> CargoxThermo { get; set; }
        public Nullable<decimal> CombUnidadIni { get; set; }
        public Nullable<decimal> CombUnidadFin { get; set; }
        public Nullable<decimal> CombUnidadInc { get; set; }
        public Nullable<decimal> CombUreaIni { get; set; }
        public Nullable<decimal> CombUreaFin { get; set; }
        public Nullable<decimal> CombUreaInc { get; set; }
        public Nullable<decimal> CombRefriIni { get; set; }
        public Nullable<decimal> CombRefriFin { get; set; }
        public Nullable<decimal> CombRefriInc { get; set; }
        public Nullable<decimal> ImporteFacturar2 { get; set; }
        public Nullable<System.DateTime> FechaEmision2 { get; set; }
        public string ContratoAplica { get; set; }
        public Nullable<System.DateTime> FechaInicio2 { get; set; }
        public Nullable<System.DateTime> FechaFin2 { get; set; }
        public Nullable<bool> Cancelado { get; set; }
        public Nullable<decimal> CargoxTelemetria2 { get; set; }
        public Nullable<decimal> CargoAbusos2 { get; set; }
        public Nullable<decimal> CargoCombustible2 { get; set; }
        public Nullable<decimal> CargoCombustibleTracto2 { get; set; }
        public Nullable<decimal> CargoCombustibleTermo2 { get; set; }
        public Nullable<decimal> CargoCombustibleUrea2 { get; set; }
    }
}
