//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilmanttod
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public string Tarea { get; set; }
        public string ArticuloSE { get; set; }
        public string Agente { get; set; }
        public Nullable<decimal> PrecioD { get; set; }
        public string Duracion { get; set; }
        public Nullable<bool> TieneGarantia { get; set; }
        public string TipoGarantia { get; set; }
        public string ProveedorGD { get; set; }
    }
}
