//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilmanttoru
    {
        public int ID { get; set; }
        public int RenglonIDRef { get; set; }
        public string ArticuloR { get; set; }
        public string SerieR { get; set; }
        public string TipoR { get; set; }
        public string ModeloR { get; set; }
        public string AnoR { get; set; }
        public string MarcaR { get; set; }
        public string ColorR { get; set; }
        public string PlacasR { get; set; }
        public string CarroceriaR { get; set; }
        public Nullable<decimal> CantidadUnidadR { get; set; }
        public string UnidadR { get; set; }
        public int IDInterno { get; set; }
    }
}
