//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilfacturacionct
    {
        public string PID { get; set; }
        public Nullable<System.DateTime> FechaInicialC { get; set; }
        public Nullable<System.DateTime> FechaFinalC { get; set; }
        public string TipoFacturaC { get; set; }
        public string TipoDetalleC { get; set; }
        public string MovimientoC { get; set; }
        public string SucursalC { get; set; }
        public Nullable<System.DateTime> FechaEmisionC { get; set; }
        public string ReferenciaC { get; set; }
        public string ConceptoC { get; set; }
        public string ObservacionesC { get; set; }
    }
}
