//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilmanttosolref
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public string Articulo { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<int> RenglonIDMod { get; set; }
        public string ServicioD { get; set; }
        public Nullable<decimal> PrecioD { get; set; }
        public string Almacen { get; set; }
        public Nullable<decimal> CantidadUnidad { get; set; }
        public string Unidad { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public string Tarea { get; set; }
        public string Proveedor { get; set; }
        public Nullable<bool> TieneGarantia { get; set; }
        public string TipoGarantia { get; set; }
        public string ListaPrecios { get; set; }
        public string Descripcion2 { get; set; }
        public string CodigoTarea { get; set; }
    }
}
