//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilcontrolflotap
    {
        public string PID { get; set; }
        public string ConceptoP { get; set; }
        public Nullable<decimal> IngresoPP { get; set; }
        public Nullable<decimal> CostoPP { get; set; }
        public Nullable<decimal> UtilidadPP { get; set; }
        public Nullable<decimal> MBPP { get; set; }
        public string EquipoP { get; set; }
        public int Interno { get; set; }
    }
}
