//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilcontrolflotamov
    {
        public string PID { get; set; }
        public string Modulo { get; set; }
        public int ID { get; set; }
        public string MovAplica { get; set; }
        public string Concepto { get; set; }
        public string Equipo { get; set; }
        public string Contacto { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
    }
}
