//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculo
    {
        public string Vehiculo1 { get; set; }
        public string Descripcion { get; set; }
        public string Estatus { get; set; }
        public string Placas { get; set; }
        public string Placas2 { get; set; }
        public bool Utilizado { get; set; }
        public string Chofer { get; set; }
        public Nullable<decimal> Volumen { get; set; }
        public Nullable<decimal> Peso { get; set; }
    }
}
