//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventamatfaltante
    {
        public int ID { get; set; }
        public int RenglonIDM { get; set; }
        public string Articulo { get; set; }
        public Nullable<decimal> CantidadUnidad { get; set; }
        public string Unidad { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Faltante { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> CostoFaltante { get; set; }
        public Nullable<decimal> ImporteCargoExtra { get; set; }
        public string Clasificacion { get; set; }
        public string Proveedor { get; set; }
        public Nullable<bool> AnticipoReq { get; set; }
        public Nullable<bool> Emergencia { get; set; }
        public Nullable<decimal> Pendiente { get; set; }
    }
}
