//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventanotacredobjetivo
    {
        public int IDInterno { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<int> NoPeriodo { get; set; }
        public string Periodo { get; set; }
        public string Linea { get; set; }
        public string SubLinea { get; set; }
        public string Marca { get; set; }
        public string Articulo { get; set; }
        public string Contacto { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> ImporteDesc { get; set; }
        public Nullable<int> IDMovAplica { get; set; }
        public Nullable<bool> Cancelado { get; set; }
    }
}
