//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventaddescuento
    {
        public int ID { get; set; }
        public int RenglonID { get; set; }
        public string NombrePromo { get; set; }
        public string Articulo { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public string TipoAplicacion { get; set; }
        public string MovAplicaNota { get; set; }
        public string ConceptoNota { get; set; }
        public Nullable<decimal> PorcApoyoProv { get; set; }
        public string MovApoyoProv { get; set; }
        public string ConceptoApoyoProv { get; set; }
    }
}
