//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vermovrastreod
    {
        public int dIDInterno { get; set; }
        public int dPID { get; set; }
        public string dModulo { get; set; }
        public int dID { get; set; }
        public string dMov { get; set; }
        public string dFolio { get; set; }
        public bool dCancelado { get; set; }
        public string dModuloDescripcion { get; set; }
    }
}
