//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vermovrastreoo
    {
        public int oIDInterno { get; set; }
        public int oPID { get; set; }
        public string oModulo { get; set; }
        public int oID { get; set; }
        public string oMov { get; set; }
        public string oFolio { get; set; }
        public bool oCancelado { get; set; }
        public string oModuloDescripcion { get; set; }
    }
}
