//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class webchat
    {
        public int id { get; set; }
        public string de { get; set; }
        public string para { get; set; }
        public string mensaje { get; set; }
        public Nullable<System.DateTime> enviar { get; set; }
        public Nullable<int> recibido { get; set; }
    }
}
