//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wfusuario
    {
        public string Modulo { get; set; }
        public string Mov { get; set; }
        public string Estatus { get; set; }
        public int ID { get; set; }
        public string Usuario { get; set; }
    
        public virtual usuario usuario1 { get; set; }
    }
}
