//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xmlcfdisugerir
    {
        public int PID { get; set; }
        public string UUID { get; set; }
        public string RFC { get; set; }
        public string Serie { get; set; }
        public string Folio { get; set; }
        public string Importe { get; set; }
        public string Fecha { get; set; }
        public string Moneda { get; set; }
        public string SATEstado { get; set; }
    }
}
