//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xmlcfdi
    {
        public string UUID { get; set; }
        public string version { get; set; }
        public string FechaTimbrad { get; set; }
        public string selloCFD { get; set; }
        public string selloSAT { get; set; }
        public string noCertificadSAT { get; set; }
        public string Empresa { get; set; }
        public string Sucursal { get; set; }
        public string Modulo { get; set; }
        public string ID { get; set; }
        public string Renglon { get; set; }
        public string Mov { get; set; }
        public string Folio { get; set; }
        public string Ruta { get; set; }
        public string Cversion { get; set; }
        public string CnoCertificado { get; set; }
        public string Cserie { get; set; }
        public string Cfecha { get; set; }
        public string Cfolio { get; set; }
        public string CformaDePago { get; set; }
        public string CsubTotal { get; set; }
        public string Cdescuento { get; set; }
        public string CmotivoDescuento { get; set; }
        public string Ctotal { get; set; }
        public string CtipoDeComprobante { get; set; }
        public string CmetodoDePago { get; set; }
        public string CLugarExpedicion { get; set; }
        public string CNumCtaPago { get; set; }
        public string CMoneda { get; set; }
        public string CTipoCambio { get; set; }
        public string Csello { get; set; }
        public string Emisorrfc { get; set; }
        public string Emisornombre { get; set; }
        public string EmisorDFiscalcalle { get; set; }
        public string EmisorDFiscalnoExterior { get; set; }
        public string EmisorDFiscalnoInterior { get; set; }
        public string EmisorDFiscalcolonia { get; set; }
        public string EmisorDFiscalmunicipio { get; set; }
        public string EmisorDFiscalestado { get; set; }
        public string EmisorDFiscalpais { get; set; }
        public string EmisorDFiscalcodigoPostal { get; set; }
        public string EmisorEEcalle { get; set; }
        public string EmisorEEnoExterior { get; set; }
        public string EmisorEElocalidad { get; set; }
        public string EmisorEEcolonia { get; set; }
        public string EmisorEEmunicipio { get; set; }
        public string EmisorEEestado { get; set; }
        public string EmisorEEpais { get; set; }
        public string EmisorEEcodigoPostal { get; set; }
        public string EmisorEEnoInterior { get; set; }
        public string EmisorRFRegimen { get; set; }
        public string Receptorrfc { get; set; }
        public string Receptornombre { get; set; }
        public string ReceptorDomcalle { get; set; }
        public string ReceptorDomnoExterior { get; set; }
        public string ReceptorDomnoInterior { get; set; }
        public string ReceptorDomcolonia { get; set; }
        public string ReceptorDommunicipio { get; set; }
        public string ReceptorDomestado { get; set; }
        public string ReceptorDompais { get; set; }
        public string ReceptorDomcodigoPostal { get; set; }
        public string ImpuestostotalImpuestosTrasladados { get; set; }
        public string Archivo { get; set; }
        public string SATEstatus { get; set; }
        public string SATEstado { get; set; }
        public string Certificado { get; set; }
        public string CondicionesDePago { get; set; }
        public string TipoRelacion { get; set; }
        public string CfdiRelacionadoUUID { get; set; }
        public string RegimenFiscal { get; set; }
        public string UsoCFDI { get; set; }
        public string ResidenciaFiscal { get; set; }
        public string CertifNumRegIdTribicado { get; set; }
        public string TrasladoImpuesto { get; set; }
        public string Confirmacion { get; set; }
    }
}
