//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xmlcfdicg
    {
        public string Empresa { get; set; }
        public string Sucursal { get; set; }
        public int cgID { get; set; }
        public string xmlID { get; set; }
        public string RFCEmisor { get; set; }
        public string FolioFiscal { get; set; }
        public string SerieConsecutivo { get; set; }
        public string FechaTimbrado { get; set; }
        public string TotalXML { get; set; }
        public string MonedaXML { get; set; }
        public string MetodoDePagoXML { get; set; }
        public string CondicionDePagoXML { get; set; }
        public string FormaDePagoXML { get; set; }
    }
}
