//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xmlcfdigasto
    {
        public string Empresa { get; set; }
        public string Sucursal { get; set; }
        public int cggastoID { get; set; }
        public int cggastoRenglonID { get; set; }
        public string cggastoxmlID { get; set; }
        public string cggastoRFCEmisor { get; set; }
        public string cggastoFolioFiscal { get; set; }
        public string cggastoSerieConsecutivo { get; set; }
        public string cggastoFechaTimbrado { get; set; }
        public string cggastoTotalXML { get; set; }
        public string cggastoMonedaXML { get; set; }
    }
}
