//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_SDMMatto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xmlcfdiventa
    {
        public string Empresa { get; set; }
        public string Sucursal { get; set; }
        public int VentaID { get; set; }
        public string xmlID { get; set; }
        public string Renglon { get; set; }
        public string RFCEmisor { get; set; }
        public string FolioFiscal { get; set; }
        public string SerieConsecutivo { get; set; }
        public string FechaTimbrado { get; set; }
        public string Total { get; set; }
        public string Moneda { get; set; }
    }
}
